############################################################
## RGMII
############################################################
set_property PACKAGE_PIN AB15 [get_ports rgmii_0_rxc]
set_property PACKAGE_PIN Y13  [get_ports rgmii_0_txc]
set_property PACKAGE_PIN W13  [get_ports rgmii_0_tx_en]    
set_property PACKAGE_PIN W15  [get_ports {rgmii_0_txd[0]}]
set_property PACKAGE_PIN Y15  [get_ports {rgmii_0_txd[1]}]
set_property PACKAGE_PIN Y17  [get_ports {rgmii_0_txd[2]}]
set_property PACKAGE_PIN AA17 [get_ports {rgmii_0_txd[3]}]
set_property PACKAGE_PIN AB16 [get_ports rgmii_0_rx_dv]
set_property PACKAGE_PIN AB17 [get_ports {rgmii_0_rxd[0]}]
set_property PACKAGE_PIN AA15 [get_ports {rgmii_0_rxd[1]}]
set_property PACKAGE_PIN Y16  [get_ports {rgmii_0_rxd[2]}]
set_property PACKAGE_PIN W16  [get_ports {rgmii_0_rxd[3]}]
set_property PACKAGE_PIN AC14 [get_ports rgmii_1_rxc]
set_property PACKAGE_PIN AA14 [get_ports rgmii_1_txc]
set_property PACKAGE_PIN AC16 [get_ports rgmii_1_tx_en]
set_property PACKAGE_PIN AA13 [get_ports {rgmii_1_txd[0]}]
set_property PACKAGE_PIN AA12 [get_ports {rgmii_1_txd[1]}]
set_property PACKAGE_PIN Y12  [get_ports {rgmii_1_txd[2]}]
set_property PACKAGE_PIN AC17 [get_ports {rgmii_1_txd[3]}]
set_property PACKAGE_PIN AF17 [get_ports rgmii_1_rx_dv]
set_property PACKAGE_PIN AD16 [get_ports {rgmii_1_rxd[0]}]
set_property PACKAGE_PIN AE17 [get_ports {rgmii_1_rxd[1]}]
set_property PACKAGE_PIN AD15 [get_ports {rgmii_1_rxd[2]}]
set_property PACKAGE_PIN AE16 [get_ports {rgmii_1_rxd[3]}]
set_property PACKAGE_PIN AC13 [get_ports rgmii_2_rxc]
set_property PACKAGE_PIN AB11 [get_ports rgmii_2_txc]
set_property PACKAGE_PIN AF14 [get_ports rgmii_2_tx_en]
set_property PACKAGE_PIN AF15 [get_ports {rgmii_2_txd[0]}]
set_property PACKAGE_PIN AE13 [get_ports {rgmii_2_txd[1]}]
set_property PACKAGE_PIN AD13 [get_ports {rgmii_2_txd[2]}]
set_property PACKAGE_PIN Y11  [get_ports {rgmii_2_txd[3]}]
set_property PACKAGE_PIN AD14 [get_ports rgmii_2_rx_dv]
set_property PACKAGE_PIN AE15 [get_ports {rgmii_2_rxd[0]}]
set_property PACKAGE_PIN AB14 [get_ports {rgmii_2_rxd[1]}]
set_property PACKAGE_PIN AF13 [get_ports {rgmii_2_rxd[2]}]
set_property PACKAGE_PIN AB12 [get_ports {rgmii_2_rxd[3]}]
set_property PACKAGE_PIN AC12 [get_ports rgmii_3_rxc]
set_property PACKAGE_PIN AC11 [get_ports rgmii_3_txc]
set_property PACKAGE_PIN AE12 [get_ports rgmii_3_tx_en]
set_property PACKAGE_PIN AB10 [get_ports {rgmii_3_txd[0]}]
set_property PACKAGE_PIN AE10 [get_ports {rgmii_3_txd[1]}]
set_property PACKAGE_PIN Y10  [get_ports {rgmii_3_txd[2]}]
set_property PACKAGE_PIN AA10 [get_ports {rgmii_3_txd[3]}]
set_property PACKAGE_PIN AF12 [get_ports rgmii_3_rx_dv]
set_property PACKAGE_PIN AD10 [get_ports {rgmii_3_rxd[0]}]
set_property PACKAGE_PIN AF10 [get_ports {rgmii_3_rxd[1]}]
set_property PACKAGE_PIN AD11 [get_ports {rgmii_3_rxd[2]}]
set_property PACKAGE_PIN AE11 [get_ports {rgmii_3_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_rx_dv]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_0_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_1_rx_dv]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_1_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_2_rx_dv]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_2_rxd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_rxc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_txc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_txd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_txd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_txd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_txd[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_3_rx_dv]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rxd[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rxd[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rxd[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {rgmii_3_rxd[3]}]

set_property PACKAGE_PIN W14 [get_ports rgmii_0_mdc]
set_property PACKAGE_PIN W17 [get_ports rgmii_0_mdio]
set_property PACKAGE_PIN K11 [get_ports rgmii_1_mdc]
set_property PACKAGE_PIN H8 [get_ports rgmii_1_mdio]
set_property PACKAGE_PIN F7 [get_ports rgmii_2_mdc]
set_property PACKAGE_PIN C8 [get_ports rgmii_2_mdio]
set_property PACKAGE_PIN C7 [get_ports rgmii_3_mdc]
set_property PACKAGE_PIN A2 [get_ports rgmii_3_mdio]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_mdc]
set_property IOSTANDARD LVCMOS25 [get_ports rgmii_0_mdio]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_1_mdc]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_1_mdio]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_2_mdc]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_2_mdio]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_3_mdc]
set_property IOSTANDARD LVCMOS15 [get_ports rgmii_3_mdio]

set_property PACKAGE_PIN AF23 [get_ports rgmii_phy_int]
set_property PACKAGE_PIN AE23 [get_ports rgmii_phy_rstn]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_phy_int]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_phy_rstn]

##
# sfp 1000baseX
##
set_property PACKAGE_PIN W6 [get_ports sfp_refclk_clk_p]
set_property PACKAGE_PIN W5 [get_ports sfp_refclk_clk_n]

create_clock -period 8 [get_ports sfp_refclk_clk_p]

# the port0
set_property PACKAGE_PIN AD7 [get_ports sfp_0_rxn]
set_property PACKAGE_PIN AD8 [get_ports sfp_0_rxp]
set_property PACKAGE_PIN AF7 [get_ports sfp_0_txn]
set_property PACKAGE_PIN AF8 [get_ports sfp_0_txp]

# the port1
set_property PACKAGE_PIN AE5 [get_ports sfp_1_rxn]
set_property PACKAGE_PIN AE6 [get_ports sfp_1_rxp]
set_property PACKAGE_PIN AF3 [get_ports sfp_1_txn]
set_property PACKAGE_PIN AF4 [get_ports sfp_1_txp]

# the port2
set_property PACKAGE_PIN AC5 [get_ports sfp_2_rxn]
set_property PACKAGE_PIN AC6 [get_ports sfp_2_rxp]
set_property PACKAGE_PIN AE1 [get_ports sfp_2_txn]
set_property PACKAGE_PIN AE2 [get_ports sfp_2_txp]

# the port3
set_property PACKAGE_PIN AD3 [get_ports sfp_3_rxn]
set_property PACKAGE_PIN AD4 [get_ports sfp_3_rxp]
set_property PACKAGE_PIN AC1 [get_ports sfp_3_txn]
set_property PACKAGE_PIN AC2 [get_ports sfp_3_txp]

############################################################
## LED + PMOD + BUTTON + SWITCH
############################################################
set_property PACKAGE_PIN AB24 [get_ports {pl_led[0]}]
set_property PACKAGE_PIN AA24 [get_ports {pl_led[1]}]
set_property PACKAGE_PIN AF24 [get_ports {pl_pmod[0]}]
set_property PACKAGE_PIN AD24 [get_ports {pl_pmod[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_pmod[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pl_pmod[1]}]
