module packet_input_pipeline
#(
    parameter C_S_AXIS_RXD_TDATA_WIDTH = 32,
    parameter C_M_AXIS_TXD_TDATA_WIDTH = 256,
    parameter C_S_AXIS_RXS_TDATA_WIDTH = 32,
    parameter C_M_AXIS_TXC_TDATA_WIDTH = 32,
    parameter C_S_AXIS_TUSER_WIDTH     = 128,
    parameter C_M_AXIS_TUSER_WIDTH     = 128,
    parameter ACTION_TUPLE_WIDTH       = 128

)
(
    // Users to add ports here
    input wire s_axis_rxd_aclk,
    input wire s_axis_rxd_aresetn,
    input wire s_axis_txd_aclk,
    input wire s_axis_txd_aresetn,

    // eth rgmii
    output wire  													s_axis_rxd_0_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_0_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_0_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_0_tkeep,
    input wire  													s_axis_rxd_0_tlast,
    input wire  													s_axis_rxd_0_tvalid,
	output wire  													s_axis_rxd_1_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_1_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_1_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_1_tkeep,
    input wire  													s_axis_rxd_1_tlast,
    input wire  													s_axis_rxd_1_tvalid,
	output wire  													s_axis_rxd_2_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_2_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_2_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_2_tkeep,
    input wire  													s_axis_rxd_2_tlast,
    input wire  													s_axis_rxd_2_tvalid,
	output wire  													s_axis_rxd_3_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_3_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_3_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_3_tkeep,
    input wire  													s_axis_rxd_3_tlast,
    input wire  													s_axis_rxd_3_tvalid,

    // eth 1000baseX
    output wire  													s_axis_rxd_4_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_4_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_4_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_4_tkeep,
    input wire  													s_axis_rxd_4_tlast,
    input wire  													s_axis_rxd_4_tvalid,
	output wire  													s_axis_rxd_5_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_5_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_5_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_5_tkeep,
    input wire  													s_axis_rxd_5_tlast,
    input wire  													s_axis_rxd_5_tvalid,
	output wire  													s_axis_rxd_6_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_6_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_6_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_6_tkeep,
    input wire  													s_axis_rxd_6_tlast,
    input wire  													s_axis_rxd_6_tvalid,
	output wire  													s_axis_rxd_7_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_7_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_7_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_7_tkeep,
    input wire  													s_axis_rxd_7_tlast,
    input wire  													s_axis_rxd_7_tvalid,

    // eth rgmii	
	output      													s_axis_rxs_0_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_0_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_0_tkeep,
    input       													s_axis_rxs_0_tlast,
    input       													s_axis_rxs_0_tvalid,
    output      													s_axis_rxs_1_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_1_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_1_tkeep,
    input       													s_axis_rxs_1_tlast,
    input       													s_axis_rxs_1_tvalid,
	output      													s_axis_rxs_2_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_2_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_2_tkeep,
    input       													s_axis_rxs_2_tlast,
    input       													s_axis_rxs_2_tvalid,
	output      													s_axis_rxs_3_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_3_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_3_tkeep,
    input       													s_axis_rxs_3_tlast,
    input       													s_axis_rxs_3_tvalid,

    // eth 1000baseX
	output      													s_axis_rxs_4_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_4_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_4_tkeep,
    input       													s_axis_rxs_4_tlast,
    input       													s_axis_rxs_4_tvalid,
    output      													s_axis_rxs_5_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_5_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_5_tkeep,
    input       													s_axis_rxs_5_tlast,
    input       													s_axis_rxs_5_tvalid,
	output      													s_axis_rxs_6_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_6_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_6_tkeep,
    input       													s_axis_rxs_6_tlast,
    input       													s_axis_rxs_6_tvalid,
	output      													s_axis_rxs_7_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_7_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_7_tkeep,
    input       													s_axis_rxs_7_tlast,
    input       													s_axis_rxs_7_tvalid,

// ---------------------------------------------------------------------------
    // dma rgmii
    output wire  													s_axis_mm2s_0_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_0_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_0_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_0_tkeep,
    input wire  													s_axis_mm2s_0_tlast,
    input wire  													s_axis_mm2s_0_tvalid,
	output wire  													s_axis_mm2s_1_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_1_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_1_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_1_tkeep,
    input wire  													s_axis_mm2s_1_tlast,
    input wire  													s_axis_mm2s_1_tvalid,
	output wire  													s_axis_mm2s_2_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_2_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_2_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_2_tkeep,
    input wire  													s_axis_mm2s_2_tlast,
    input wire  													s_axis_mm2s_2_tvalid,
	output wire  													s_axis_mm2s_3_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_3_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_3_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_3_tkeep,
    input wire  													s_axis_mm2s_3_tlast,
    input wire  													s_axis_mm2s_3_tvalid,

    // dma 1000baseX
    output wire  													s_axis_mm2s_4_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_4_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_4_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_4_tkeep,
    input wire  													s_axis_mm2s_4_tlast,
    input wire  													s_axis_mm2s_4_tvalid,
	output wire  													s_axis_mm2s_5_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_5_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_5_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_5_tkeep,
    input wire  													s_axis_mm2s_5_tlast,
    input wire  													s_axis_mm2s_5_tvalid,
	output wire  													s_axis_mm2s_6_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_6_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_6_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_6_tkeep,
    input wire  													s_axis_mm2s_6_tlast,
    input wire  													s_axis_mm2s_6_tvalid,
	output wire  													s_axis_mm2s_7_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_7_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_7_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_7_tkeep,
    input wire  													s_axis_mm2s_7_tlast,
    input wire  													s_axis_mm2s_7_tvalid,

    // dma rgmii	
	output      													s_axis_ctrl_0_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_0_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_0_tkeep,
    input       													s_axis_ctrl_0_tlast,
    input       													s_axis_ctrl_0_tvalid,
    output      													s_axis_ctrl_1_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_1_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_1_tkeep,
    input       													s_axis_ctrl_1_tlast,
    input       													s_axis_ctrl_1_tvalid,
	output      													s_axis_ctrl_2_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_2_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_2_tkeep,
    input       													s_axis_ctrl_2_tlast,
    input       													s_axis_ctrl_2_tvalid,
	output      													s_axis_ctrl_3_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_3_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_3_tkeep,
    input       													s_axis_ctrl_3_tlast,
    input       													s_axis_ctrl_3_tvalid,

    // dma 1000baseX
	output      													s_axis_ctrl_4_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_4_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_4_tkeep,
    input       													s_axis_ctrl_4_tlast,
    input       													s_axis_ctrl_4_tvalid,
    output      													s_axis_ctrl_5_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_5_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_5_tkeep,
    input       													s_axis_ctrl_5_tlast,
    input       													s_axis_ctrl_5_tvalid,
	output      													s_axis_ctrl_6_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_6_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_6_tkeep,
    input       													s_axis_ctrl_6_tlast,
    input       													s_axis_ctrl_6_tvalid,
	output      													s_axis_ctrl_7_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_7_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_7_tkeep,
    input       													s_axis_ctrl_7_tlast,
    input       													s_axis_ctrl_7_tvalid,

// ---------------------------------------------------------------------------

    output wire  													m_axis_txd_0_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 					m_axis_txd_0_tdata,
    output wire [C_M_AXIS_TUSER_WIDTH-1 : 0] 					    m_axis_txd_0_tuser,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 				m_axis_txd_0_tkeep,
    output wire  													m_axis_txd_0_tlast,
    input wire  													m_axis_txd_0_tready,	
	output      													m_axis_txc_0_tvalid,
	output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]      					m_axis_txc_0_tdata,
	output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]  					m_axis_txc_0_tkeep,
	output     														m_axis_txc_0_tlast,
	input      														m_axis_txc_0_tready,
 
    output   [ACTION_TUPLE_WIDTH-1:0]                               tuple_out_flowstream_data,
    output                                                          tuple_out_flowstream_valid
	
   );

    wire  													        quad_mid_axis_tvalid[3:0];
    wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 					        quad_mid_axis_tdata[3:0];
    wire [C_M_AXIS_TUSER_WIDTH-1 : 0] 					            quad_mid_axis_tuser[3:0];
    wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 				        quad_mid_axis_tkeep[3:0];
    wire  													        quad_mid_axis_tlast[3:0];
    wire  													        quad_mid_axis_tready[3:0];	

    packet_input_quad
    #(
        .AXIS_CONTROL_IF_ENABLE        (0),
        .DEFAULT_TUSER_ENABLE          (1),
        .QUAD_BASE_ADDRESS             (0),
        .C_S_AXIS_RXD_TDATA_WIDTH      (C_S_AXIS_RXD_TDATA_WIDTH),
        .C_M_AXIS_TXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_S_AXIS_RXS_TDATA_WIDTH      (C_S_AXIS_RXS_TDATA_WIDTH),
        .C_M_AXIS_TXC_TDATA_WIDTH      (C_M_AXIS_TXC_TDATA_WIDTH),
        .C_S_AXIS_TUSER_WIDTH          (C_S_AXIS_TUSER_WIDTH),
        .C_M_AXIS_TUSER_WIDTH          (C_M_AXIS_TUSER_WIDTH),
        .ACTION_TUPLE_WIDTH            (ACTION_TUPLE_WIDTH)
    ) packet_input_rgmii
    (
        .s_axis_rxd_aclk             (s_axis_rxd_aclk    ),
        .s_axis_rxd_aresetn          (s_axis_rxd_aresetn ),
        .s_axis_txd_aclk             (s_axis_txd_aclk    ),
        .s_axis_txd_aresetn          (s_axis_txd_aresetn ),
        .s_axis_rxd_0_tready         (s_axis_rxd_0_tready),
        .s_axis_rxd_0_tdata          (s_axis_rxd_0_tdata ),
        .s_axis_rxd_0_tuser          (),
        .s_axis_rxd_0_tkeep          (s_axis_rxd_0_tkeep ),
        .s_axis_rxd_0_tlast          (s_axis_rxd_0_tlast ),
        .s_axis_rxd_0_tvalid         (s_axis_rxd_0_tvalid),
        .s_axis_rxd_1_tready         (s_axis_rxd_1_tready),
        .s_axis_rxd_1_tdata          (s_axis_rxd_1_tdata ),
        .s_axis_rxd_1_tuser          (),
        .s_axis_rxd_1_tkeep          (s_axis_rxd_1_tkeep ),
        .s_axis_rxd_1_tlast          (s_axis_rxd_1_tlast ),
        .s_axis_rxd_1_tvalid         (s_axis_rxd_1_tvalid),
        .s_axis_rxd_2_tready         (s_axis_rxd_2_tready),
        .s_axis_rxd_2_tdata          (s_axis_rxd_2_tdata ),
        .s_axis_rxd_2_tuser          (),
        .s_axis_rxd_2_tkeep          (s_axis_rxd_2_tkeep ),
        .s_axis_rxd_2_tlast          (s_axis_rxd_2_tlast ),
        .s_axis_rxd_2_tvalid         (s_axis_rxd_2_tvalid),
        .s_axis_rxd_3_tready         (s_axis_rxd_3_tready),
        .s_axis_rxd_3_tdata          (s_axis_rxd_3_tdata ),
        .s_axis_rxd_3_tuser          (),
        .s_axis_rxd_3_tkeep          (s_axis_rxd_3_tkeep ),
        .s_axis_rxd_3_tlast          (s_axis_rxd_3_tlast ),
        .s_axis_rxd_3_tvalid         (s_axis_rxd_3_tvalid),
        .s_axis_rxs_0_tready         (s_axis_rxs_0_tready),
        .s_axis_rxs_1_tready         (s_axis_rxs_1_tready),
        .s_axis_rxs_2_tready         (s_axis_rxs_2_tready),
        .s_axis_rxs_3_tready         (s_axis_rxs_3_tready),
        .m_axis_txd_0_tvalid         (quad_mid_axis_tvalid[0]),
        .m_axis_txd_0_tdata          (quad_mid_axis_tdata[0]),
        .m_axis_txd_0_tuser          (quad_mid_axis_tuser[0]),
        .m_axis_txd_0_tkeep          (quad_mid_axis_tkeep[0]),
        .m_axis_txd_0_tlast          (quad_mid_axis_tlast[0]),
        .m_axis_txd_0_tready	     (quad_mid_axis_tready[0])
    );

    packet_input_quad
    #(
        .AXIS_CONTROL_IF_ENABLE        (0),
        .DEFAULT_TUSER_ENABLE          (1),
        .QUAD_BASE_ADDRESS             (4),
        .C_S_AXIS_RXD_TDATA_WIDTH      (C_S_AXIS_RXD_TDATA_WIDTH),
        .C_M_AXIS_TXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_S_AXIS_RXS_TDATA_WIDTH      (C_S_AXIS_RXS_TDATA_WIDTH),
        .C_M_AXIS_TXC_TDATA_WIDTH      (C_M_AXIS_TXC_TDATA_WIDTH),
        .C_S_AXIS_TUSER_WIDTH          (C_S_AXIS_TUSER_WIDTH),
        .C_M_AXIS_TUSER_WIDTH          (C_M_AXIS_TUSER_WIDTH),
        .ACTION_TUPLE_WIDTH            (ACTION_TUPLE_WIDTH)
    ) packet_input_1000baseX
    (
        .s_axis_rxd_aclk             (s_axis_rxd_aclk    ),
        .s_axis_rxd_aresetn          (s_axis_rxd_aresetn ),
        .s_axis_txd_aclk             (s_axis_txd_aclk    ),
        .s_axis_txd_aresetn          (s_axis_txd_aresetn ),
        .s_axis_rxd_0_tready         (s_axis_rxd_4_tready),
        .s_axis_rxd_0_tdata          (s_axis_rxd_4_tdata ),
        .s_axis_rxd_0_tuser          (),
        .s_axis_rxd_0_tkeep          (s_axis_rxd_4_tkeep ),
        .s_axis_rxd_0_tlast          (s_axis_rxd_4_tlast ),
        .s_axis_rxd_0_tvalid         (s_axis_rxd_4_tvalid),
        .s_axis_rxd_1_tready         (s_axis_rxd_5_tready),
        .s_axis_rxd_1_tdata          (s_axis_rxd_5_tdata ),
        .s_axis_rxd_1_tuser          (),
        .s_axis_rxd_1_tkeep          (s_axis_rxd_5_tkeep ),
        .s_axis_rxd_1_tlast          (s_axis_rxd_5_tlast ),
        .s_axis_rxd_1_tvalid         (s_axis_rxd_5_tvalid),
        .s_axis_rxd_2_tready         (s_axis_rxd_6_tready),
        .s_axis_rxd_2_tdata          (s_axis_rxd_6_tdata ),
        .s_axis_rxd_2_tuser          (),
        .s_axis_rxd_2_tkeep          (s_axis_rxd_6_tkeep ),
        .s_axis_rxd_2_tlast          (s_axis_rxd_6_tlast ),
        .s_axis_rxd_2_tvalid         (s_axis_rxd_6_tvalid),
        .s_axis_rxd_3_tready         (s_axis_rxd_7_tready),
        .s_axis_rxd_3_tdata          (s_axis_rxd_7_tdata ),
        .s_axis_rxd_3_tuser          (),
        .s_axis_rxd_3_tkeep          (s_axis_rxd_7_tkeep ),
        .s_axis_rxd_3_tlast          (s_axis_rxd_7_tlast ),
        .s_axis_rxd_3_tvalid         (s_axis_rxd_7_tvalid),
        .s_axis_rxs_0_tready         (s_axis_rxs_4_tready),
        .s_axis_rxs_1_tready         (s_axis_rxs_5_tready),
        .s_axis_rxs_2_tready         (s_axis_rxs_6_tready),
        .s_axis_rxs_3_tready         (s_axis_rxs_7_tready),
        .m_axis_txd_0_tvalid         (quad_mid_axis_tvalid[1]),
        .m_axis_txd_0_tdata          (quad_mid_axis_tdata[1]),
        .m_axis_txd_0_tuser          (quad_mid_axis_tuser[1]),
        .m_axis_txd_0_tkeep          (quad_mid_axis_tkeep[1]),
        .m_axis_txd_0_tlast          (quad_mid_axis_tlast[1]),
        .m_axis_txd_0_tready	     (quad_mid_axis_tready[1])
    );

    packet_input_quad
    #(
        .AXIS_CONTROL_IF_ENABLE        (0),
        .DEFAULT_TUSER_ENABLE          (1),
        .QUAD_BASE_ADDRESS             (8),
        .C_S_AXIS_RXD_TDATA_WIDTH      (C_S_AXIS_RXD_TDATA_WIDTH),
        .C_M_AXIS_TXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_S_AXIS_RXS_TDATA_WIDTH      (C_S_AXIS_RXS_TDATA_WIDTH),
        .C_M_AXIS_TXC_TDATA_WIDTH      (C_M_AXIS_TXC_TDATA_WIDTH),
        .C_S_AXIS_TUSER_WIDTH          (C_S_AXIS_TUSER_WIDTH),
        .C_M_AXIS_TUSER_WIDTH          (C_M_AXIS_TUSER_WIDTH),
        .ACTION_TUPLE_WIDTH            (ACTION_TUPLE_WIDTH)
    ) packet_input_rgmii_dma
    (
        .s_axis_rxd_aclk             (s_axis_rxd_aclk    ),
        .s_axis_rxd_aresetn          (s_axis_rxd_aresetn ),
        .s_axis_txd_aclk             (s_axis_txd_aclk    ),
        .s_axis_txd_aresetn          (s_axis_txd_aresetn ),
        .s_axis_rxd_0_tready         (s_axis_mm2s_0_tready ),
        .s_axis_rxd_0_tdata          (s_axis_mm2s_0_tdata ),
        .s_axis_rxd_0_tuser          (),
        .s_axis_rxd_0_tkeep          (s_axis_mm2s_0_tkeep ),
        .s_axis_rxd_0_tlast          (s_axis_mm2s_0_tlast ),
        .s_axis_rxd_0_tvalid         (s_axis_mm2s_0_tvalid),
        .s_axis_rxd_1_tready         (s_axis_mm2s_1_tready),
        .s_axis_rxd_1_tdata          (s_axis_mm2s_1_tdata ),
        .s_axis_rxd_1_tuser          (),
        .s_axis_rxd_1_tkeep          (s_axis_mm2s_1_tkeep ),
        .s_axis_rxd_1_tlast          (s_axis_mm2s_1_tlast ),
        .s_axis_rxd_1_tvalid         (s_axis_mm2s_1_tvalid),
        .s_axis_rxd_2_tready         (s_axis_mm2s_2_tready),
        .s_axis_rxd_2_tdata          (s_axis_mm2s_2_tdata ),
        .s_axis_rxd_2_tuser          (),
        .s_axis_rxd_2_tkeep          (s_axis_mm2s_2_tkeep ),
        .s_axis_rxd_2_tlast          (s_axis_mm2s_2_tlast ),
        .s_axis_rxd_2_tvalid         (s_axis_mm2s_2_tvalid),
        .s_axis_rxd_3_tready         (s_axis_mm2s_3_tready),
        .s_axis_rxd_3_tdata          (s_axis_mm2s_3_tdata ),
        .s_axis_rxd_3_tuser          (),
        .s_axis_rxd_3_tkeep          (s_axis_mm2s_3_tkeep ),
        .s_axis_rxd_3_tlast          (s_axis_mm2s_3_tlast ),
        .s_axis_rxd_3_tvalid         (s_axis_mm2s_3_tvalid),
        .s_axis_rxs_0_tready         (s_axis_ctrl_0_tready),
        .s_axis_rxs_1_tready         (s_axis_ctrl_1_tready),
        .s_axis_rxs_2_tready         (s_axis_ctrl_2_tready),
        .s_axis_rxs_3_tready         (s_axis_ctrl_3_tready),
        .m_axis_txd_0_tvalid         (quad_mid_axis_tvalid[2]),
        .m_axis_txd_0_tdata          (quad_mid_axis_tdata[2]),
        .m_axis_txd_0_tuser          (quad_mid_axis_tuser[2]),
        .m_axis_txd_0_tkeep          (quad_mid_axis_tkeep[2]),
        .m_axis_txd_0_tlast          (quad_mid_axis_tlast[2]),
        .m_axis_txd_0_tready	     (quad_mid_axis_tready[2])
    );

    packet_input_quad
    #(
        .AXIS_CONTROL_IF_ENABLE        (0),
        .DEFAULT_TUSER_ENABLE          (1),
        .QUAD_BASE_ADDRESS             (12),
        .C_S_AXIS_RXD_TDATA_WIDTH      (C_S_AXIS_RXD_TDATA_WIDTH),
        .C_M_AXIS_TXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_S_AXIS_RXS_TDATA_WIDTH      (C_S_AXIS_RXS_TDATA_WIDTH),
        .C_M_AXIS_TXC_TDATA_WIDTH      (C_M_AXIS_TXC_TDATA_WIDTH),
        .C_S_AXIS_TUSER_WIDTH          (C_S_AXIS_TUSER_WIDTH),
        .C_M_AXIS_TUSER_WIDTH          (C_M_AXIS_TUSER_WIDTH),
        .ACTION_TUPLE_WIDTH            (ACTION_TUPLE_WIDTH)
    ) packet_input_1000baseX_dma
    (
        .s_axis_rxd_aclk             (s_axis_rxd_aclk    ),
        .s_axis_rxd_aresetn          (s_axis_rxd_aresetn ),
        .s_axis_txd_aclk             (s_axis_txd_aclk    ),
        .s_axis_txd_aresetn          (s_axis_txd_aresetn ),
        .s_axis_rxd_0_tready         (s_axis_mm2s_4_tready),
        .s_axis_rxd_0_tdata          (s_axis_mm2s_4_tdata ),
        .s_axis_rxd_0_tuser          (),
        .s_axis_rxd_0_tkeep          (s_axis_mm2s_4_tkeep ),
        .s_axis_rxd_0_tlast          (s_axis_mm2s_4_tlast ),
        .s_axis_rxd_0_tvalid         (s_axis_mm2s_4_tvalid),
        .s_axis_rxd_1_tready         (s_axis_mm2s_5_tready),
        .s_axis_rxd_1_tdata          (s_axis_mm2s_5_tdata ),
        .s_axis_rxd_1_tuser          (),
        .s_axis_rxd_1_tkeep          (s_axis_mm2s_5_tkeep ),
        .s_axis_rxd_1_tlast          (s_axis_mm2s_5_tlast ),
        .s_axis_rxd_1_tvalid         (s_axis_mm2s_5_tvalid),
        .s_axis_rxd_2_tready         (s_axis_mm2s_6_tready),
        .s_axis_rxd_2_tdata          (s_axis_mm2s_6_tdata ),
        .s_axis_rxd_2_tuser          (),
        .s_axis_rxd_2_tkeep          (s_axis_mm2s_6_tkeep ),
        .s_axis_rxd_2_tlast          (s_axis_mm2s_6_tlast ),
        .s_axis_rxd_2_tvalid         (s_axis_mm2s_6_tvalid),
        .s_axis_rxd_3_tready         (s_axis_mm2s_7_tready),
        .s_axis_rxd_3_tdata          (s_axis_mm2s_7_tdata ),
        .s_axis_rxd_3_tuser          (),
        .s_axis_rxd_3_tkeep          (s_axis_mm2s_7_tkeep ),
        .s_axis_rxd_3_tlast          (s_axis_mm2s_7_tlast ),
        .s_axis_rxd_3_tvalid         (s_axis_mm2s_7_tvalid),
        .s_axis_rxs_0_tready         (s_axis_ctrl_4_tready),
        .s_axis_rxs_1_tready         (s_axis_ctrl_5_tready),
        .s_axis_rxs_2_tready         (s_axis_ctrl_6_tready),
        .s_axis_rxs_3_tready         (s_axis_ctrl_7_tready),
        .m_axis_txd_0_tvalid         (quad_mid_axis_tvalid[3]),
        .m_axis_txd_0_tdata          (quad_mid_axis_tdata[3]),
        .m_axis_txd_0_tuser          (quad_mid_axis_tuser[3]),
        .m_axis_txd_0_tkeep          (quad_mid_axis_tkeep[3]),
        .m_axis_txd_0_tlast          (quad_mid_axis_tlast[3]),
        .m_axis_txd_0_tready	     (quad_mid_axis_tready[3])
    );

    packet_input_quad
    #(
        .AXIS_CONTROL_IF_ENABLE        (1),
        .DEFAULT_TUSER_ENABLE          (0),
        .QUAD_BASE_ADDRESS             (0),
        .C_S_AXIS_RXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_M_AXIS_TXD_TDATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_S_AXIS_RXS_TDATA_WIDTH      (C_S_AXIS_RXS_TDATA_WIDTH),
        .C_M_AXIS_TXC_TDATA_WIDTH      (C_M_AXIS_TXC_TDATA_WIDTH),
        .C_S_AXIS_TUSER_WIDTH          (C_S_AXIS_TUSER_WIDTH),
        .C_M_AXIS_TUSER_WIDTH          (C_M_AXIS_TUSER_WIDTH),
        .ACTION_TUPLE_WIDTH            (ACTION_TUPLE_WIDTH)
    ) packet_input_quad_out_dma
    (
        .s_axis_rxd_aclk             (s_axis_rxd_aclk   ),
        .s_axis_rxd_aresetn          (s_axis_rxd_aresetn),
        .s_axis_txd_aclk             (s_axis_txd_aclk   ),
        .s_axis_txd_aresetn          (s_axis_txd_aresetn),
        .s_axis_rxd_0_tready         (quad_mid_axis_tready[0]),
        .s_axis_rxd_0_tdata          (quad_mid_axis_tdata[0]),
        .s_axis_rxd_0_tuser          (quad_mid_axis_tuser[0]),
        .s_axis_rxd_0_tkeep          (quad_mid_axis_tkeep[0]),
        .s_axis_rxd_0_tlast          (quad_mid_axis_tlast[0]),
        .s_axis_rxd_0_tvalid         (quad_mid_axis_tvalid[0]),
        .s_axis_rxd_1_tready         (quad_mid_axis_tready[1]),
        .s_axis_rxd_1_tdata          (quad_mid_axis_tdata[1]),
        .s_axis_rxd_1_tuser          (quad_mid_axis_tuser[1]),
        .s_axis_rxd_1_tkeep          (quad_mid_axis_tkeep[1]),
        .s_axis_rxd_1_tlast          (quad_mid_axis_tlast[1]),
        .s_axis_rxd_1_tvalid         (quad_mid_axis_tvalid[1]),
        .s_axis_rxd_2_tready         (quad_mid_axis_tready[2]),
        .s_axis_rxd_2_tdata          (quad_mid_axis_tdata[2]),
        .s_axis_rxd_2_tuser          (quad_mid_axis_tuser[2]),
        .s_axis_rxd_2_tkeep          (quad_mid_axis_tkeep[2]),
        .s_axis_rxd_2_tlast          (quad_mid_axis_tlast[2]),
        .s_axis_rxd_2_tvalid         (quad_mid_axis_tvalid[2]),
        .s_axis_rxd_3_tready         (quad_mid_axis_tready[3]),
        .s_axis_rxd_3_tdata          (quad_mid_axis_tdata[3]),
        .s_axis_rxd_3_tuser          (quad_mid_axis_tuser[3]),
        .s_axis_rxd_3_tkeep          (quad_mid_axis_tkeep[3]),
        .s_axis_rxd_3_tlast          (quad_mid_axis_tlast[3]),
        .s_axis_rxd_3_tvalid         (quad_mid_axis_tvalid[3]),
        .s_axis_rxs_0_tready         (),
        .s_axis_rxs_1_tready         (),
        .s_axis_rxs_2_tready         (),
        .s_axis_rxs_3_tready         (),
        .m_axis_txd_0_tvalid         (m_axis_txd_0_tvalid),
        .m_axis_txd_0_tdata          (m_axis_txd_0_tdata ),
        .m_axis_txd_0_tuser          (m_axis_txd_0_tuser ),
        .m_axis_txd_0_tkeep          (m_axis_txd_0_tkeep ),
        .m_axis_txd_0_tlast          (m_axis_txd_0_tlast ),
        .m_axis_txd_0_tready	     (m_axis_txd_0_tready),
        .m_axis_txc_0_tvalid         (m_axis_txc_0_tvalid),
        .m_axis_txc_0_tdata          (m_axis_txc_0_tdata ),
        .m_axis_txc_0_tkeep          (m_axis_txc_0_tkeep ),
        .m_axis_txc_0_tlast          (m_axis_txc_0_tlast ),
        .m_axis_txc_0_tready         (m_axis_txc_0_tready),
        .tuple_out_flowstream_data   (tuple_out_flowstream_data),
        .tuple_out_flowstream_valid  (tuple_out_flowstream_valid)
    );

 endmodule
