//-------------------------------------------------------------------
// AXI4 interface wrapper for packet processing pipeline.
//-------------------------------------------------------------------

module packet_output_pipeline#(
    // Parameters of Axi Slave Bus Interface S_AXI_LITE
    parameter integer C_S_AXI_LITE_DATA_WIDTH = 32,
    parameter integer C_S_AXI_LITE_ADDR_WIDTH = 27,
    // Parameters of Axi Slave Bus Interface S_AXIS_RXD
    parameter integer C_S_AXIS_RXD_TDATA_WIDTH = 256,
    parameter integer C_S_AXIS_RXS_TDATA_WIDTH = 32,
    // Parameters of Axi Master Bus Interface M_AXIS_TXD
    parameter integer C_M_AXIS_TXD_TDATA_WIDTH = 32,
    parameter integer C_M_AXIS_TXC_TDATA_WIDTH = 32,
    parameter integer ACTION_TUPLE_WIDTH       = 128
)
(
    // Users to add ports here
    input wire                                          s_axis_rxd_aclk,
    input wire                                          s_axis_rxd_aresetn,
    input wire                                          s_axis_txd_aclk,
    input wire                                          s_axis_txd_aresetn,
    // User ports ends
    // Do not modify the ports beyond this line

    // Ports of Axi Slave Bus Interface S_AXI_LITE
    input wire                                          s_axi_lite_aclk,
    input wire                                          s_axi_lite_aresetn,
    input wire [C_S_AXI_LITE_ADDR_WIDTH-1 : 0]          s_axi_lite_awaddr,
    input wire [2 : 0]                                  s_axi_lite_awprot,
    input wire                                          s_axi_lite_awvalid,
    output wire                                         s_axi_lite_awready,
    input wire [C_S_AXI_LITE_DATA_WIDTH-1 : 0]          s_axi_lite_wdata,
    input wire [(C_S_AXI_LITE_DATA_WIDTH/8)-1 : 0]      s_axi_lite_wstrb,
    input wire                                          s_axi_lite_wvalid,
    output wire                                         s_axi_lite_wready,
    output wire [1 : 0]                                 s_axi_lite_bresp,
    output wire                                         s_axi_lite_bvalid,
    input wire                                          s_axi_lite_bready,
    input wire [C_S_AXI_LITE_ADDR_WIDTH-1 : 0]          s_axi_lite_araddr,
    input wire [2 : 0]                                  s_axi_lite_arprot,
    input wire                                          s_axi_lite_arvalid,
    output wire                                         s_axi_lite_arready,
    output wire [C_S_AXI_LITE_DATA_WIDTH-1 : 0]         s_axi_lite_rdata,
    output wire [1 : 0]                                 s_axi_lite_rresp,
    output wire                                         s_axi_lite_rvalid,
    input wire                                          s_axi_lite_rready,

    output wire                                         s_axis_rxd_0_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0]         s_axis_rxd_0_tdata,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0]     s_axis_rxd_0_tkeep,
    input wire                                          s_axis_rxd_0_tlast,
    input wire                                          s_axis_rxd_0_tvalid,
    output                                              s_axis_rxs_0_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]              s_axis_rxs_0_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]          s_axis_rxs_0_tkeep,
    input                                               s_axis_rxs_0_tlast,
    input                                               s_axis_rxs_0_tvalid,

    output wire                                         m_axis_txd_0_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_0_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_0_tkeep,
    output wire                                         m_axis_txd_0_tlast,
    input wire                                          m_axis_txd_0_tready,
	output wire                                         m_axis_txd_1_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_1_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_1_tkeep,
    output wire                                         m_axis_txd_1_tlast,
    input wire                                          m_axis_txd_1_tready,
    output wire                                         m_axis_txd_2_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_2_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_2_tkeep,
    output wire                                         m_axis_txd_2_tlast,
    input wire                                          m_axis_txd_2_tready,
	output wire                                         m_axis_txd_3_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_3_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_3_tkeep,
    output wire                                         m_axis_txd_3_tlast,
    input wire                                          m_axis_txd_3_tready,
    output wire                                         m_axis_txd_4_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_4_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_4_tkeep,
    output wire                                         m_axis_txd_4_tlast,
    input wire                                          m_axis_txd_4_tready,
	output wire                                         m_axis_txd_5_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_5_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_5_tkeep,
    output wire                                         m_axis_txd_5_tlast,
    input wire                                          m_axis_txd_5_tready,
    output wire                                         m_axis_txd_6_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_6_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_6_tkeep,
    output wire                                         m_axis_txd_6_tlast,
    input wire                                          m_axis_txd_6_tready,
	output wire                                         m_axis_txd_7_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_7_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_7_tkeep,
    output wire                                         m_axis_txd_7_tlast,
    input wire                                          m_axis_txd_7_tready,
    
    output                                              m_axis_txc_0_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_0_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_0_tkeep,
    output                                              m_axis_txc_0_tlast,
    input                                               m_axis_txc_0_tready,
    output                                              m_axis_txc_1_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_1_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_1_tkeep,
    output                                              m_axis_txc_1_tlast,
    input                                               m_axis_txc_1_tready,
    output                                              m_axis_txc_2_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_2_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_2_tkeep,
    output                                              m_axis_txc_2_tlast,
    input                                               m_axis_txc_2_tready,
    output                                              m_axis_txc_3_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_3_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_3_tkeep,
    output                                              m_axis_txc_3_tlast,
    input                                               m_axis_txc_3_tready,
    output                                              m_axis_txc_4_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_4_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_4_tkeep,
    output                                              m_axis_txc_4_tlast,
    input                                               m_axis_txc_4_tready,
    output                                              m_axis_txc_5_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_5_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_5_tkeep,
    output                                              m_axis_txc_5_tlast,
    input                                               m_axis_txc_5_tready,
    output                                              m_axis_txc_6_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_6_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_6_tkeep,
    output                                              m_axis_txc_6_tlast,
    input                                               m_axis_txc_6_tready,
    output                                              m_axis_txc_7_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_7_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_7_tkeep,
    output                                              m_axis_txc_7_tlast,
    input                                               m_axis_txc_7_tready,
    
    output wire  										m_axis_s2mm_0_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_0_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_0_tkeep,
    output wire  										m_axis_s2mm_0_tlast,
    input wire  										m_axis_s2mm_0_tready,
    output wire  										m_axis_s2mm_1_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_1_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_1_tkeep,
    output wire  										m_axis_s2mm_1_tlast,
    input wire  										m_axis_s2mm_1_tready,
    output wire  										m_axis_s2mm_2_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_2_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_2_tkeep,
    output wire  										m_axis_s2mm_2_tlast,
    input wire  										m_axis_s2mm_2_tready,
    output wire  										m_axis_s2mm_3_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_3_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_3_tkeep,
    output wire  										m_axis_s2mm_3_tlast,
    input wire  										m_axis_s2mm_3_tready,
    output wire  										m_axis_s2mm_4_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_4_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_4_tkeep,
    output wire  										m_axis_s2mm_4_tlast,
    input wire  										m_axis_s2mm_4_tready,
    output wire  										m_axis_s2mm_5_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_5_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_5_tkeep,
    output wire  										m_axis_s2mm_5_tlast,
    input wire  										m_axis_s2mm_5_tready,
    output wire  										m_axis_s2mm_6_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_6_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_6_tkeep,
    output wire  										m_axis_s2mm_6_tlast,
    input wire  										m_axis_s2mm_6_tready,
    output wire  										m_axis_s2mm_7_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_7_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_7_tkeep,
    output wire  										m_axis_s2mm_7_tlast,
    input wire  										m_axis_s2mm_7_tready,
    
    output wire  										m_axis_s2mm_sts_0_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_0_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_0_tkeep,
    output wire  										m_axis_s2mm_sts_0_tlast,
    input wire  										m_axis_s2mm_sts_0_tready,
    output wire  										m_axis_s2mm_sts_1_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_1_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_1_tkeep,
    output wire  										m_axis_s2mm_sts_1_tlast,
    input wire  										m_axis_s2mm_sts_1_tready,
    output wire  										m_axis_s2mm_sts_2_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_2_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_2_tkeep,
    output wire  										m_axis_s2mm_sts_2_tlast,
    input wire  										m_axis_s2mm_sts_2_tready,
    output wire  										m_axis_s2mm_sts_3_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_3_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_3_tkeep,
    output wire  										m_axis_s2mm_sts_3_tlast,
    input wire  										m_axis_s2mm_sts_3_tready,
    output wire  										m_axis_s2mm_sts_4_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_4_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_4_tkeep,
    output wire  										m_axis_s2mm_sts_4_tlast,
    input wire  										m_axis_s2mm_sts_4_tready,
    output wire  										m_axis_s2mm_sts_5_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_5_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_5_tkeep,
    output wire  										m_axis_s2mm_sts_5_tlast,
    input wire  										m_axis_s2mm_sts_5_tready,
    output wire  										m_axis_s2mm_sts_6_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_6_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_6_tkeep,
    output wire  										m_axis_s2mm_sts_6_tlast,
    input wire  										m_axis_s2mm_sts_6_tready,
    output wire  										m_axis_s2mm_sts_7_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_7_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_7_tkeep,
    output wire  										m_axis_s2mm_sts_7_tlast,
    input wire  										m_axis_s2mm_sts_7_tready,
    
    input   [ACTION_TUPLE_WIDTH-1:0]                    tuple_in_flowstream_data,
    input                                               tuple_in_flowstream_valid
    
   );

    wire axis_aclk = s_axis_rxd_aclk;
    wire axis_aresetn = s_axis_rxd_aresetn;

    assign s_axis_rxs_0_tready = 1;
   
    onet_core_output
    #(
        .C_S_AXIS_DATA_WIDTH      (C_S_AXIS_RXD_TDATA_WIDTH),
        .C_S_AXIS_USER_WIDTH      (ACTION_TUPLE_WIDTH),
        .C_M_AXIS_DATA_WIDTH      (C_M_AXIS_TXD_TDATA_WIDTH),
        .C_M_AXIS_USER_WIDTH      (ACTION_TUPLE_WIDTH),
        .ACTION_TUPLE_WIDTH       (ACTION_TUPLE_WIDTH)
    ) onet_core_output_inst
    (
        .axis_aclk                          (axis_aclk),
        .axis_aresetn                       (axis_aresetn),
        .s_axis_rxd_tvalid                  (s_axis_rxd_0_tvalid),
        .s_axis_rxd_tready                  (s_axis_rxd_0_tready),
        .s_axis_rxd_tdata                   (s_axis_rxd_0_tdata),
        .s_axis_rxd_tkeep                   (s_axis_rxd_0_tkeep),
        .s_axis_rxd_tlast                   (s_axis_rxd_0_tlast),

        .m_axis_eth_txd_tdata_0             (m_axis_txd_0_tdata  ),
        .m_axis_eth_txd_tvalid_0            (m_axis_txd_0_tvalid ),
        .m_axis_eth_txd_tlast_0             (m_axis_txd_0_tlast  ),
        .m_axis_eth_txd_tkeep_0             (m_axis_txd_0_tkeep  ),
        .m_axis_eth_txd_tready_0            (m_axis_txd_0_tready ),
        .m_axis_eth_txc_tdata_0             (m_axis_txc_0_tdata  ),
        .m_axis_eth_txc_tvalid_0            (m_axis_txc_0_tvalid ),
        .m_axis_eth_txc_tlast_0             (m_axis_txc_0_tlast  ),
        .m_axis_eth_txc_tkeep_0             (m_axis_txc_0_tkeep  ),
        .m_axis_eth_txc_tready_0            (m_axis_txc_0_tready ),
        .m_axis_dma_txd_tdata_0             (m_axis_s2mm_0_tdata  ),
        .m_axis_dma_txd_tvalid_0            (m_axis_s2mm_0_tvalid ),
        .m_axis_dma_txd_tlast_0             (m_axis_s2mm_0_tlast  ),
        .m_axis_dma_txd_tkeep_0             (m_axis_s2mm_0_tkeep  ),
        .m_axis_dma_txd_tready_0            (m_axis_s2mm_0_tready ),
        .m_axis_dma_txc_tdata_0             (m_axis_s2mm_sts_0_tdata  ),
        .m_axis_dma_txc_tvalid_0            (m_axis_s2mm_sts_0_tvalid ),
        .m_axis_dma_txc_tlast_0             (m_axis_s2mm_sts_0_tlast  ),
        .m_axis_dma_txc_tkeep_0             (m_axis_s2mm_sts_0_tkeep  ),
        .m_axis_dma_txc_tready_0            (m_axis_s2mm_sts_0_tready ),
        .m_axis_eth_txd_tdata_1             (m_axis_txd_1_tdata  ),
        .m_axis_eth_txd_tvalid_1            (m_axis_txd_1_tvalid ),
        .m_axis_eth_txd_tlast_1             (m_axis_txd_1_tlast  ),
        .m_axis_eth_txd_tkeep_1             (m_axis_txd_1_tkeep  ),
        .m_axis_eth_txd_tready_1            (m_axis_txd_1_tready ),
        .m_axis_eth_txc_tdata_1             (m_axis_txc_1_tdata  ),
        .m_axis_eth_txc_tvalid_1            (m_axis_txc_1_tvalid ),
        .m_axis_eth_txc_tlast_1             (m_axis_txc_1_tlast  ),
        .m_axis_eth_txc_tkeep_1             (m_axis_txc_1_tkeep  ),
        .m_axis_eth_txc_tready_1            (m_axis_txc_1_tready ),
        .m_axis_dma_txd_tdata_1             (m_axis_s2mm_1_tdata  ),
        .m_axis_dma_txd_tvalid_1            (m_axis_s2mm_1_tvalid ),
        .m_axis_dma_txd_tlast_1             (m_axis_s2mm_1_tlast  ),
        .m_axis_dma_txd_tkeep_1             (m_axis_s2mm_1_tkeep  ),
        .m_axis_dma_txd_tready_1            (m_axis_s2mm_1_tready ),
        .m_axis_dma_txc_tdata_1             (m_axis_s2mm_sts_1_tdata  ),
        .m_axis_dma_txc_tvalid_1            (m_axis_s2mm_sts_1_tvalid ),
        .m_axis_dma_txc_tlast_1             (m_axis_s2mm_sts_1_tlast  ),
        .m_axis_dma_txc_tkeep_1             (m_axis_s2mm_sts_1_tkeep  ),
        .m_axis_dma_txc_tready_1            (m_axis_s2mm_sts_1_tready ),
        .m_axis_eth_txd_tdata_2             (m_axis_txd_2_tdata  ),
        .m_axis_eth_txd_tvalid_2            (m_axis_txd_2_tvalid ),
        .m_axis_eth_txd_tlast_2             (m_axis_txd_2_tlast  ),
        .m_axis_eth_txd_tkeep_2             (m_axis_txd_2_tkeep  ),
        .m_axis_eth_txd_tready_2            (m_axis_txd_2_tready ),
        .m_axis_eth_txc_tdata_2             (m_axis_txc_2_tdata  ),
        .m_axis_eth_txc_tvalid_2            (m_axis_txc_2_tvalid ),
        .m_axis_eth_txc_tlast_2             (m_axis_txc_2_tlast  ),
        .m_axis_eth_txc_tkeep_2             (m_axis_txc_2_tkeep  ),
        .m_axis_eth_txc_tready_2            (m_axis_txc_2_tready ),
        .m_axis_dma_txd_tdata_2             (m_axis_s2mm_2_tdata  ),
        .m_axis_dma_txd_tvalid_2            (m_axis_s2mm_2_tvalid ),
        .m_axis_dma_txd_tlast_2             (m_axis_s2mm_2_tlast  ),
        .m_axis_dma_txd_tkeep_2             (m_axis_s2mm_2_tkeep  ),
        .m_axis_dma_txd_tready_2            (m_axis_s2mm_2_tready ),
        .m_axis_dma_txc_tdata_2             (m_axis_s2mm_sts_2_tdata  ),
        .m_axis_dma_txc_tvalid_2            (m_axis_s2mm_sts_2_tvalid ),
        .m_axis_dma_txc_tlast_2             (m_axis_s2mm_sts_2_tlast  ),
        .m_axis_dma_txc_tkeep_2             (m_axis_s2mm_sts_2_tkeep  ),
        .m_axis_dma_txc_tready_2            (m_axis_s2mm_sts_2_tready ),
        .m_axis_eth_txd_tdata_3             (m_axis_txd_3_tdata  ),
        .m_axis_eth_txd_tvalid_3            (m_axis_txd_3_tvalid ),
        .m_axis_eth_txd_tlast_3             (m_axis_txd_3_tlast  ),
        .m_axis_eth_txd_tkeep_3             (m_axis_txd_3_tkeep  ),
        .m_axis_eth_txd_tready_3            (m_axis_txd_3_tready ),
        .m_axis_eth_txc_tdata_3             (m_axis_txc_3_tdata  ),
        .m_axis_eth_txc_tvalid_3            (m_axis_txc_3_tvalid ),
        .m_axis_eth_txc_tlast_3             (m_axis_txc_3_tlast  ),
        .m_axis_eth_txc_tkeep_3             (m_axis_txc_3_tkeep  ),
        .m_axis_eth_txc_tready_3            (m_axis_txc_3_tready ),
        .m_axis_dma_txd_tdata_3             (m_axis_s2mm_3_tdata  ),
        .m_axis_dma_txd_tvalid_3            (m_axis_s2mm_3_tvalid ),
        .m_axis_dma_txd_tlast_3             (m_axis_s2mm_3_tlast  ),
        .m_axis_dma_txd_tkeep_3             (m_axis_s2mm_3_tkeep  ),
        .m_axis_dma_txd_tready_3            (m_axis_s2mm_3_tready ),
        .m_axis_dma_txc_tdata_3             (m_axis_s2mm_sts_3_tdata  ),
        .m_axis_dma_txc_tvalid_3            (m_axis_s2mm_sts_3_tvalid ),
        .m_axis_dma_txc_tlast_3             (m_axis_s2mm_sts_3_tlast  ),
        .m_axis_dma_txc_tkeep_3             (m_axis_s2mm_sts_3_tkeep  ),
        .m_axis_dma_txc_tready_3            (m_axis_s2mm_sts_3_tready ),
        .m_axis_eth_txd_tdata_4             (m_axis_txd_4_tdata  ),
        .m_axis_eth_txd_tvalid_4            (m_axis_txd_4_tvalid ),
        .m_axis_eth_txd_tlast_4             (m_axis_txd_4_tlast  ),
        .m_axis_eth_txd_tkeep_4             (m_axis_txd_4_tkeep  ),
        .m_axis_eth_txd_tready_4            (m_axis_txd_4_tready ),
        .m_axis_eth_txc_tdata_4             (m_axis_txc_4_tdata  ),
        .m_axis_eth_txc_tvalid_4            (m_axis_txc_4_tvalid ),
        .m_axis_eth_txc_tlast_4             (m_axis_txc_4_tlast  ),
        .m_axis_eth_txc_tkeep_4             (m_axis_txc_4_tkeep  ),
        .m_axis_eth_txc_tready_4            (m_axis_txc_4_tready ),
        .m_axis_dma_txd_tdata_4             (m_axis_s2mm_4_tdata  ),
        .m_axis_dma_txd_tvalid_4            (m_axis_s2mm_4_tvalid ),
        .m_axis_dma_txd_tlast_4             (m_axis_s2mm_4_tlast  ),
        .m_axis_dma_txd_tkeep_4             (m_axis_s2mm_4_tkeep  ),
        .m_axis_dma_txd_tready_4            (m_axis_s2mm_4_tready ),
        .m_axis_dma_txc_tdata_4             (m_axis_s2mm_sts_4_tdata  ),
        .m_axis_dma_txc_tvalid_4            (m_axis_s2mm_sts_4_tvalid ),
        .m_axis_dma_txc_tlast_4             (m_axis_s2mm_sts_4_tlast  ),
        .m_axis_dma_txc_tkeep_4             (m_axis_s2mm_sts_4_tkeep  ),
        .m_axis_dma_txc_tready_4            (m_axis_s2mm_sts_4_tready ),
        .m_axis_eth_txd_tdata_5             (m_axis_txd_5_tdata  ),
        .m_axis_eth_txd_tvalid_5            (m_axis_txd_5_tvalid ),
        .m_axis_eth_txd_tlast_5             (m_axis_txd_5_tlast  ),
        .m_axis_eth_txd_tkeep_5             (m_axis_txd_5_tkeep  ),
        .m_axis_eth_txd_tready_5            (m_axis_txd_5_tready ),
        .m_axis_eth_txc_tdata_5             (m_axis_txc_5_tdata  ),
        .m_axis_eth_txc_tvalid_5            (m_axis_txc_5_tvalid ),
        .m_axis_eth_txc_tlast_5             (m_axis_txc_5_tlast  ),
        .m_axis_eth_txc_tkeep_5             (m_axis_txc_5_tkeep  ),
        .m_axis_eth_txc_tready_5            (m_axis_txc_5_tready ),
        .m_axis_dma_txd_tdata_5             (m_axis_s2mm_5_tdata  ),
        .m_axis_dma_txd_tvalid_5            (m_axis_s2mm_5_tvalid ),
        .m_axis_dma_txd_tlast_5             (m_axis_s2mm_5_tlast  ),
        .m_axis_dma_txd_tkeep_5             (m_axis_s2mm_5_tkeep  ),
        .m_axis_dma_txd_tready_5            (m_axis_s2mm_5_tready ),
        .m_axis_dma_txc_tdata_5             (m_axis_s2mm_sts_5_tdata  ),
        .m_axis_dma_txc_tvalid_5            (m_axis_s2mm_sts_5_tvalid ),
        .m_axis_dma_txc_tlast_5             (m_axis_s2mm_sts_5_tlast  ),
        .m_axis_dma_txc_tkeep_5             (m_axis_s2mm_sts_5_tkeep  ),
        .m_axis_dma_txc_tready_5            (m_axis_s2mm_sts_5_tready ),
        .m_axis_eth_txd_tdata_6             (m_axis_txd_6_tdata  ),
        .m_axis_eth_txd_tvalid_6            (m_axis_txd_6_tvalid ),
        .m_axis_eth_txd_tlast_6             (m_axis_txd_6_tlast  ),
        .m_axis_eth_txd_tkeep_6             (m_axis_txd_6_tkeep  ),
        .m_axis_eth_txd_tready_6            (m_axis_txd_6_tready ),
        .m_axis_eth_txc_tdata_6             (m_axis_txc_6_tdata  ),
        .m_axis_eth_txc_tvalid_6            (m_axis_txc_6_tvalid ),
        .m_axis_eth_txc_tlast_6             (m_axis_txc_6_tlast  ),
        .m_axis_eth_txc_tkeep_6             (m_axis_txc_6_tkeep  ),
        .m_axis_eth_txc_tready_6            (m_axis_txc_6_tready ),
        .m_axis_dma_txd_tdata_6             (m_axis_s2mm_6_tdata  ),
        .m_axis_dma_txd_tvalid_6            (m_axis_s2mm_6_tvalid ),
        .m_axis_dma_txd_tlast_6             (m_axis_s2mm_6_tlast  ),
        .m_axis_dma_txd_tkeep_6             (m_axis_s2mm_6_tkeep  ),
        .m_axis_dma_txd_tready_6            (m_axis_s2mm_6_tready ),
        .m_axis_dma_txc_tdata_6             (m_axis_s2mm_sts_6_tdata  ),
        .m_axis_dma_txc_tvalid_6            (m_axis_s2mm_sts_6_tvalid ),
        .m_axis_dma_txc_tlast_6             (m_axis_s2mm_sts_6_tlast  ),
        .m_axis_dma_txc_tkeep_6             (m_axis_s2mm_sts_6_tkeep  ),
        .m_axis_dma_txc_tready_6            (m_axis_s2mm_sts_6_tready ),
        .m_axis_eth_txd_tdata_7             (m_axis_txd_7_tdata  ),
        .m_axis_eth_txd_tvalid_7            (m_axis_txd_7_tvalid ),
        .m_axis_eth_txd_tlast_7             (m_axis_txd_7_tlast  ),
        .m_axis_eth_txd_tkeep_7             (m_axis_txd_7_tkeep  ),
        .m_axis_eth_txd_tready_7            (m_axis_txd_7_tready ),
        .m_axis_eth_txc_tdata_7             (m_axis_txc_7_tdata  ),
        .m_axis_eth_txc_tvalid_7            (m_axis_txc_7_tvalid ),
        .m_axis_eth_txc_tlast_7             (m_axis_txc_7_tlast  ),
        .m_axis_eth_txc_tkeep_7             (m_axis_txc_7_tkeep  ),
        .m_axis_eth_txc_tready_7            (m_axis_txc_7_tready ),
        .m_axis_dma_txd_tdata_7             (m_axis_s2mm_7_tdata  ),
        .m_axis_dma_txd_tvalid_7            (m_axis_s2mm_7_tvalid ),
        .m_axis_dma_txd_tlast_7             (m_axis_s2mm_7_tlast  ),
        .m_axis_dma_txd_tkeep_7             (m_axis_s2mm_7_tkeep  ),
        .m_axis_dma_txd_tready_7            (m_axis_s2mm_7_tready ),
        .m_axis_dma_txc_tdata_7             (m_axis_s2mm_sts_7_tdata  ),
        .m_axis_dma_txc_tvalid_7            (m_axis_s2mm_sts_7_tvalid ),
        .m_axis_dma_txc_tlast_7             (m_axis_s2mm_sts_7_tlast  ),
        .m_axis_dma_txc_tkeep_7             (m_axis_s2mm_sts_7_tkeep  ),
        .m_axis_dma_txc_tready_7            (m_axis_s2mm_sts_7_tready ),

        .tuple_in_flowstream_valid          (tuple_in_flowstream_valid),
        .tuple_in_flowstream_data           (tuple_in_flowstream_data )

    );


endmodule
