module packet_pipeline
#(
    parameter C_S_AXI_LITE_DATA_WIDTH  = 32,
    parameter C_S_AXI_LITE_ADDR_WIDTH  = 27,
    parameter C_S_AXIS_RXD_TDATA_WIDTH = 32,
    parameter C_M_AXIS_TXD_TDATA_WIDTH = 32,
    parameter C_S_AXIS_RXS_TDATA_WIDTH = 32,
    parameter C_M_AXIS_TXC_TDATA_WIDTH = 32,
    parameter C_S_AXIS_TUSER_WIDTH     = 128,
    parameter C_M_AXIS_TUSER_WIDTH     = 128,
    parameter ACTION_TUPLE_WIDTH       = 128

)
(
    // Users to add ports here
    input wire s_axis_rxd_aclk,
    input wire s_axis_rxd_aresetn,
    input wire s_axis_txd_aclk,
    input wire s_axis_txd_aresetn,

    // eth rgmii
    output wire                                                     s_axis_rxd_0_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0]                     s_axis_rxd_0_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0]                         s_axis_rxd_0_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0]                 s_axis_rxd_0_tkeep,
    input wire                                                      s_axis_rxd_0_tlast,
    input wire                                                      s_axis_rxd_0_tvalid,
    output wire  													s_axis_rxd_1_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_1_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_1_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_1_tkeep,
    input wire  													s_axis_rxd_1_tlast,
    input wire  													s_axis_rxd_1_tvalid,
    output wire  													s_axis_rxd_2_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_2_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_2_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_2_tkeep,
    input wire  													s_axis_rxd_2_tlast,
    input wire  													s_axis_rxd_2_tvalid,
    output wire  													s_axis_rxd_3_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_3_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_3_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_3_tkeep,
    input wire  													s_axis_rxd_3_tlast,
    input wire  													s_axis_rxd_3_tvalid,
    
    // eth 1000baseX
    output wire  													s_axis_rxd_4_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_4_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_4_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_4_tkeep,
    input wire  													s_axis_rxd_4_tlast,
    input wire  													s_axis_rxd_4_tvalid,
    output wire  													s_axis_rxd_5_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_5_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_5_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_5_tkeep,
    input wire  													s_axis_rxd_5_tlast,
    input wire  													s_axis_rxd_5_tvalid,
    output wire  													s_axis_rxd_6_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_6_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_6_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_6_tkeep,
    input wire  													s_axis_rxd_6_tlast,
    input wire  													s_axis_rxd_6_tvalid,
    output wire  													s_axis_rxd_7_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_rxd_7_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_rxd_7_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_rxd_7_tkeep,
    input wire  													s_axis_rxd_7_tlast,
    input wire  													s_axis_rxd_7_tvalid,
    
    // eth rgmii	
    output      													s_axis_rxs_0_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_0_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_0_tkeep,
    input       													s_axis_rxs_0_tlast,
    input       													s_axis_rxs_0_tvalid,
    output      													s_axis_rxs_1_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_1_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_1_tkeep,
    input       													s_axis_rxs_1_tlast,
    input       													s_axis_rxs_1_tvalid,
    output      													s_axis_rxs_2_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_2_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_2_tkeep,
    input       													s_axis_rxs_2_tlast,
    input       													s_axis_rxs_2_tvalid,
    output      													s_axis_rxs_3_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_3_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_3_tkeep,
    input       													s_axis_rxs_3_tlast,
    input       													s_axis_rxs_3_tvalid,
    
    // eth 1000baseX
    output      													s_axis_rxs_4_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_4_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_4_tkeep,
    input       													s_axis_rxs_4_tlast,
    input       													s_axis_rxs_4_tvalid,
    output      													s_axis_rxs_5_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_5_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_5_tkeep,
    input       													s_axis_rxs_5_tlast,
    input       													s_axis_rxs_5_tvalid,
    output      													s_axis_rxs_6_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_6_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_6_tkeep,
    input       													s_axis_rxs_6_tlast,
    input       													s_axis_rxs_6_tvalid,
    output      													s_axis_rxs_7_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_rxs_7_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_rxs_7_tkeep,
    input       													s_axis_rxs_7_tlast,
    input       													s_axis_rxs_7_tvalid,
    
    // dma rgmii
    output wire  													s_axis_mm2s_0_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_0_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_0_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_0_tkeep,
    input wire  													s_axis_mm2s_0_tlast,
    input wire  													s_axis_mm2s_0_tvalid,
    output wire  													s_axis_mm2s_1_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_1_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_1_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_1_tkeep,
    input wire  													s_axis_mm2s_1_tlast,
    input wire  													s_axis_mm2s_1_tvalid,
    output wire  													s_axis_mm2s_2_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_2_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_2_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_2_tkeep,
    input wire  													s_axis_mm2s_2_tlast,
    input wire  													s_axis_mm2s_2_tvalid,
    output wire  													s_axis_mm2s_3_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_3_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_3_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_3_tkeep,
    input wire  													s_axis_mm2s_3_tlast,
    input wire  													s_axis_mm2s_3_tvalid,
    
    // dma 1000baseX
    output wire  													s_axis_mm2s_4_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_4_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_4_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_4_tkeep,
    input wire  													s_axis_mm2s_4_tlast,
    input wire  													s_axis_mm2s_4_tvalid,
    output wire  													s_axis_mm2s_5_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_5_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_5_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_5_tkeep,
    input wire  													s_axis_mm2s_5_tlast,
    input wire  													s_axis_mm2s_5_tvalid,
    output wire  													s_axis_mm2s_6_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_6_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_6_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_6_tkeep,
    input wire  													s_axis_mm2s_6_tlast,
    input wire  													s_axis_mm2s_6_tvalid,
    output wire  													s_axis_mm2s_7_tready,
    input wire [C_S_AXIS_RXD_TDATA_WIDTH-1 : 0] 					s_axis_mm2s_7_tdata,
    input wire [C_S_AXIS_TUSER_WIDTH-1 : 0] 					    s_axis_mm2s_7_tuser,
    input wire [(C_S_AXIS_RXD_TDATA_WIDTH/8)-1 : 0] 				s_axis_mm2s_7_tkeep,
    input wire  													s_axis_mm2s_7_tlast,
    input wire  													s_axis_mm2s_7_tvalid,
    
    // dma rgmii	
    output      													s_axis_ctrl_0_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_0_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_0_tkeep,
    input       													s_axis_ctrl_0_tlast,
    input       													s_axis_ctrl_0_tvalid,
    output      													s_axis_ctrl_1_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_1_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_1_tkeep,
    input       													s_axis_ctrl_1_tlast,
    input       													s_axis_ctrl_1_tvalid,
    output      													s_axis_ctrl_2_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_2_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_2_tkeep,
    input       													s_axis_ctrl_2_tlast,
    input       													s_axis_ctrl_2_tvalid,
    output      													s_axis_ctrl_3_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_3_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_3_tkeep,
    input       													s_axis_ctrl_3_tlast,
    input       													s_axis_ctrl_3_tvalid,
    
    // dma 1000baseX
    output      													s_axis_ctrl_4_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_4_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_4_tkeep,
    input       													s_axis_ctrl_4_tlast,
    input       													s_axis_ctrl_4_tvalid,
    output      													s_axis_ctrl_5_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_5_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_5_tkeep,
    input       													s_axis_ctrl_5_tlast,
    input       													s_axis_ctrl_5_tvalid,
    output      													s_axis_ctrl_6_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_6_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_6_tkeep,
    input       													s_axis_ctrl_6_tlast,
    input       													s_axis_ctrl_6_tvalid,
    output      													s_axis_ctrl_7_tready,
    input [C_S_AXIS_RXS_TDATA_WIDTH-1 : 0]       					s_axis_ctrl_7_tdata,
    input [(C_S_AXIS_RXS_TDATA_WIDTH/8)-1 : 0]   					s_axis_ctrl_7_tkeep,
    input       													s_axis_ctrl_7_tlast,
    input       													s_axis_ctrl_7_tvalid,

    // Ports of Axi Slave Bus Interface S_AXI_LITE
    input wire                                          s_axi_lite_aclk,
    input wire                                          s_axi_lite_aresetn,
    input wire [C_S_AXI_LITE_ADDR_WIDTH-1 : 0]          s_axi_lite_awaddr,
    input wire [2 : 0]                                  s_axi_lite_awprot,
    input wire                                          s_axi_lite_awvalid,
    output wire                                         s_axi_lite_awready,
    input wire [C_S_AXI_LITE_DATA_WIDTH-1 : 0]          s_axi_lite_wdata,
    input wire [(C_S_AXI_LITE_DATA_WIDTH/8)-1 : 0]      s_axi_lite_wstrb,
    input wire                                          s_axi_lite_wvalid,
    output wire                                         s_axi_lite_wready,
    output wire [1 : 0]                                 s_axi_lite_bresp,
    output wire                                         s_axi_lite_bvalid,
    input wire                                          s_axi_lite_bready,
    input wire [C_S_AXI_LITE_ADDR_WIDTH-1 : 0]          s_axi_lite_araddr,
    input wire [2 : 0]                                  s_axi_lite_arprot,
    input wire                                          s_axi_lite_arvalid,
    output wire                                         s_axi_lite_arready,
    output wire [C_S_AXI_LITE_DATA_WIDTH-1 : 0]         s_axi_lite_rdata,
    output wire [1 : 0]                                 s_axi_lite_rresp,
    output wire                                         s_axi_lite_rvalid,
    input wire                                          s_axi_lite_rready,

    // sdnet axi_bus
    input [7:0]                                         control_S_AXI_AWADDR,
    input [0:0]                                         control_S_AXI_AWVALID,
    output [0:0]                                        control_S_AXI_AWREADY,
    input [31:0]                                        control_S_AXI_WDATA,
    input [3:0]                                         control_S_AXI_WSTRB,
    input [0:0]                                         control_S_AXI_WVALID,
    output [0:0]                                        control_S_AXI_WREADY,
    output [1:0]                                        control_S_AXI_BRESP,
    output [0:0]                                        control_S_AXI_BVALID,
    input [0:0]                                         control_S_AXI_BREADY,
    input [7:0]                                         control_S_AXI_ARADDR,
    input [0:0]                                         control_S_AXI_ARVALID,
    output [0:0]                                        control_S_AXI_ARREADY,
    output [31:0]                                       control_S_AXI_RDATA,
    output [1:0]                                        control_S_AXI_RRESP,
    output [0:0]                                        control_S_AXI_RVALID,
    input [0:0]                                         control_S_AXI_RREADY,

    output wire                                         m_axis_txd_0_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_0_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_0_tkeep,
    output wire                                         m_axis_txd_0_tlast,
    input wire                                          m_axis_txd_0_tready,
	output wire                                         m_axis_txd_1_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_1_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_1_tkeep,
    output wire                                         m_axis_txd_1_tlast,
    input wire                                          m_axis_txd_1_tready,
    output wire                                         m_axis_txd_2_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_2_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_2_tkeep,
    output wire                                         m_axis_txd_2_tlast,
    input wire                                          m_axis_txd_2_tready,
	output wire                                         m_axis_txd_3_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_3_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_3_tkeep,
    output wire                                         m_axis_txd_3_tlast,
    input wire                                          m_axis_txd_3_tready,
    output wire                                         m_axis_txd_4_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_4_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_4_tkeep,
    output wire                                         m_axis_txd_4_tlast,
    input wire                                          m_axis_txd_4_tready,
	output wire                                         m_axis_txd_5_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_5_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_5_tkeep,
    output wire                                         m_axis_txd_5_tlast,
    input wire                                          m_axis_txd_5_tready,
    output wire                                         m_axis_txd_6_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_6_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_6_tkeep,
    output wire                                         m_axis_txd_6_tlast,
    input wire                                          m_axis_txd_6_tready,
	output wire                                         m_axis_txd_7_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0]        m_axis_txd_7_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0]    m_axis_txd_7_tkeep,
    output wire                                         m_axis_txd_7_tlast,
    input wire                                          m_axis_txd_7_tready,
    
    output                                              m_axis_txc_0_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_0_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_0_tkeep,
    output                                              m_axis_txc_0_tlast,
    input                                               m_axis_txc_0_tready,
    output                                              m_axis_txc_1_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_1_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_1_tkeep,
    output                                              m_axis_txc_1_tlast,
    input                                               m_axis_txc_1_tready,
    output                                              m_axis_txc_2_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_2_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_2_tkeep,
    output                                              m_axis_txc_2_tlast,
    input                                               m_axis_txc_2_tready,
    output                                              m_axis_txc_3_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_3_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_3_tkeep,
    output                                              m_axis_txc_3_tlast,
    input                                               m_axis_txc_3_tready,
    output                                              m_axis_txc_4_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_4_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_4_tkeep,
    output                                              m_axis_txc_4_tlast,
    input                                               m_axis_txc_4_tready,
    output                                              m_axis_txc_5_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_5_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_5_tkeep,
    output                                              m_axis_txc_5_tlast,
    input                                               m_axis_txc_5_tready,
    output                                              m_axis_txc_6_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_6_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_6_tkeep,
    output                                              m_axis_txc_6_tlast,
    input                                               m_axis_txc_6_tready,
    output                                              m_axis_txc_7_tvalid,
    output [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0]             m_axis_txc_7_tdata,
    output [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0]         m_axis_txc_7_tkeep,
    output                                              m_axis_txc_7_tlast,
    input                                               m_axis_txc_7_tready,
    
    output wire  										m_axis_s2mm_0_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_0_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_0_tkeep,
    output wire  										m_axis_s2mm_0_tlast,
    input wire  										m_axis_s2mm_0_tready,
    output wire  										m_axis_s2mm_1_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_1_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_1_tkeep,
    output wire  										m_axis_s2mm_1_tlast,
    input wire  										m_axis_s2mm_1_tready,
    output wire  										m_axis_s2mm_2_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_2_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_2_tkeep,
    output wire  										m_axis_s2mm_2_tlast,
    input wire  										m_axis_s2mm_2_tready,
    output wire  										m_axis_s2mm_3_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_3_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_3_tkeep,
    output wire  										m_axis_s2mm_3_tlast,
    input wire  										m_axis_s2mm_3_tready,
    output wire  										m_axis_s2mm_4_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_4_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_4_tkeep,
    output wire  										m_axis_s2mm_4_tlast,
    input wire  										m_axis_s2mm_4_tready,
    output wire  										m_axis_s2mm_5_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_5_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_5_tkeep,
    output wire  										m_axis_s2mm_5_tlast,
    input wire  										m_axis_s2mm_5_tready,
    output wire  										m_axis_s2mm_6_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_6_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_6_tkeep,
    output wire  										m_axis_s2mm_6_tlast,
    input wire  										m_axis_s2mm_6_tready,
    output wire  										m_axis_s2mm_7_tvalid,
    output wire [C_M_AXIS_TXD_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_7_tdata,
    output wire [(C_M_AXIS_TXD_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_7_tkeep,
    output wire  										m_axis_s2mm_7_tlast,
    input wire  										m_axis_s2mm_7_tready,
    
    output wire  										m_axis_s2mm_sts_0_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_0_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_0_tkeep,
    output wire  										m_axis_s2mm_sts_0_tlast,
    input wire  										m_axis_s2mm_sts_0_tready,
    output wire  										m_axis_s2mm_sts_1_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_1_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_1_tkeep,
    output wire  										m_axis_s2mm_sts_1_tlast,
    input wire  										m_axis_s2mm_sts_1_tready,
    output wire  										m_axis_s2mm_sts_2_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_2_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_2_tkeep,
    output wire  										m_axis_s2mm_sts_2_tlast,
    input wire  										m_axis_s2mm_sts_2_tready,
    output wire  										m_axis_s2mm_sts_3_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_3_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_3_tkeep,
    output wire  										m_axis_s2mm_sts_3_tlast,
    input wire  										m_axis_s2mm_sts_3_tready,
    output wire  										m_axis_s2mm_sts_4_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_4_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_4_tkeep,
    output wire  										m_axis_s2mm_sts_4_tlast,
    input wire  										m_axis_s2mm_sts_4_tready,
    output wire  										m_axis_s2mm_sts_5_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_5_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_5_tkeep,
    output wire  										m_axis_s2mm_sts_5_tlast,
    input wire  										m_axis_s2mm_sts_5_tready,
    output wire  										m_axis_s2mm_sts_6_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_6_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_6_tkeep,
    output wire  										m_axis_s2mm_sts_6_tlast,
    input wire  										m_axis_s2mm_sts_6_tready,
    output wire  										m_axis_s2mm_sts_7_tvalid,
    output wire [C_M_AXIS_TXC_TDATA_WIDTH-1 : 0] 		m_axis_s2mm_sts_7_tdata,
    output wire [(C_M_AXIS_TXC_TDATA_WIDTH/8)-1 : 0] 	m_axis_s2mm_sts_7_tkeep,
    output wire  										m_axis_s2mm_sts_7_tlast,
    input wire  										m_axis_s2mm_sts_7_tready

   );

   localparam AXIS_SDNET_DATA_WIDTH = 256;

   wire      										    m_axis_sdnet_txc_tvalid;
   wire [31 : 0]      			                        m_axis_sdnet_txc_tdata;
   wire [3 : 0]  			                            m_axis_sdnet_txc_tkeep;
   wire     										    m_axis_sdnet_txc_tlast;
   wire                                                 m_axis_sdnet_txc_tready;
   wire  											    s_axis_sdnet_rxd_tready;
   wire  											    s_axis_sdnet_rxd_tvalid;
   wire [255 : 0] 					                    s_axis_sdnet_rxd_tdata;
   wire [31 : 0] 				                        s_axis_sdnet_rxd_tkeep;
   wire  											    s_axis_sdnet_rxd_tlast;
   wire  											    m_axis_sdnet_txd_tready;
   wire  											    m_axis_sdnet_txd_tvalid;
   wire [255 : 0] 					                    m_axis_sdnet_txd_tdata;
   wire [31 : 0] 				                        m_axis_sdnet_txd_tkeep;
   wire  											    m_axis_sdnet_txd_tlast;
   wire [ACTION_TUPLE_WIDTH-1:0]                        sdnet_metadata_in_data;
   wire                                                 sdnet_metadata_in_valid;
   wire [ACTION_TUPLE_WIDTH-1:0]                        sdnet_metadata_out_data;
   wire                                                 sdnet_metadata_out_valid;

   wire clk_line        = s_axis_rxd_aclk;
   wire clk_lookup      = s_axi_lite_aclk;
   wire clk_control     = s_axi_lite_aclk;
   wire clk_line_rst    = ~s_axis_rxd_aresetn;
   wire clk_lookup_rst  = ~s_axi_lite_aresetn;
   wire clk_control_rst = ~s_axi_lite_aresetn;


   packet_input_pipeline
   #(
       .C_S_AXIS_RXD_TDATA_WIDTH   (C_S_AXIS_RXD_TDATA_WIDTH),
       .C_M_AXIS_TXD_TDATA_WIDTH   (AXIS_SDNET_DATA_WIDTH),
       .C_S_AXIS_RXS_TDATA_WIDTH   (C_S_AXIS_RXS_TDATA_WIDTH),
       .C_M_AXIS_TXC_TDATA_WIDTH   (C_M_AXIS_TXC_TDATA_WIDTH),
       .C_S_AXIS_TUSER_WIDTH       (ACTION_TUPLE_WIDTH),
       .C_M_AXIS_TUSER_WIDTH       (ACTION_TUPLE_WIDTH),
       .ACTION_TUPLE_WIDTH         (ACTION_TUPLE_WIDTH)
   ) packet_input_pipeline_inst
   (
       .s_axis_rxd_aclk                (s_axis_rxd_aclk           ),
       .s_axis_rxd_aresetn             (s_axis_rxd_aresetn        ),
       .s_axis_txd_aclk                (s_axis_txd_aclk           ),
       .s_axis_txd_aresetn             (s_axis_txd_aresetn        ),
       .s_axis_rxd_0_tready            (s_axis_rxd_0_tready       ),
       .s_axis_rxd_0_tdata             (s_axis_rxd_0_tdata        ),
       .s_axis_rxd_0_tuser             (s_axis_rxd_0_tuser        ),
       .s_axis_rxd_0_tkeep             (s_axis_rxd_0_tkeep        ),
       .s_axis_rxd_0_tlast             (s_axis_rxd_0_tlast        ),
       .s_axis_rxd_0_tvalid            (s_axis_rxd_0_tvalid       ),
       .s_axis_rxd_1_tready            (s_axis_rxd_1_tready       ),
       .s_axis_rxd_1_tdata             (s_axis_rxd_1_tdata        ),
       .s_axis_rxd_1_tuser             (s_axis_rxd_1_tuser        ),
       .s_axis_rxd_1_tkeep             (s_axis_rxd_1_tkeep        ),
       .s_axis_rxd_1_tlast             (s_axis_rxd_1_tlast        ),
       .s_axis_rxd_1_tvalid            (s_axis_rxd_1_tvalid       ),
       .s_axis_rxd_2_tready            (s_axis_rxd_2_tready       ),
       .s_axis_rxd_2_tdata             (s_axis_rxd_2_tdata        ),
       .s_axis_rxd_2_tuser             (s_axis_rxd_2_tuser        ),
       .s_axis_rxd_2_tkeep             (s_axis_rxd_2_tkeep        ),
       .s_axis_rxd_2_tlast             (s_axis_rxd_2_tlast        ),
       .s_axis_rxd_2_tvalid            (s_axis_rxd_2_tvalid       ),
       .s_axis_rxd_3_tready            (s_axis_rxd_3_tready       ),
       .s_axis_rxd_3_tdata             (s_axis_rxd_3_tdata        ),
       .s_axis_rxd_3_tuser             (s_axis_rxd_3_tuser        ),
       .s_axis_rxd_3_tkeep             (s_axis_rxd_3_tkeep        ),
       .s_axis_rxd_3_tlast             (s_axis_rxd_3_tlast        ),
       .s_axis_rxd_3_tvalid            (s_axis_rxd_3_tvalid       ),
       .s_axis_rxd_4_tready            (s_axis_rxd_4_tready       ),
       .s_axis_rxd_4_tdata             (s_axis_rxd_4_tdata        ),
       .s_axis_rxd_4_tuser             (s_axis_rxd_4_tuser        ),
       .s_axis_rxd_4_tkeep             (s_axis_rxd_4_tkeep        ),
       .s_axis_rxd_4_tlast             (s_axis_rxd_4_tlast        ),
       .s_axis_rxd_4_tvalid            (s_axis_rxd_4_tvalid       ),
       .s_axis_rxd_5_tready            (s_axis_rxd_5_tready       ),
       .s_axis_rxd_5_tdata             (s_axis_rxd_5_tdata        ),
       .s_axis_rxd_5_tuser             (s_axis_rxd_5_tuser        ),
       .s_axis_rxd_5_tkeep             (s_axis_rxd_5_tkeep        ),
       .s_axis_rxd_5_tlast             (s_axis_rxd_5_tlast        ),
       .s_axis_rxd_5_tvalid            (s_axis_rxd_5_tvalid       ),
       .s_axis_rxd_6_tready            (s_axis_rxd_6_tready       ),
       .s_axis_rxd_6_tdata             (s_axis_rxd_6_tdata        ),
       .s_axis_rxd_6_tuser             (s_axis_rxd_6_tuser        ),
       .s_axis_rxd_6_tkeep             (s_axis_rxd_6_tkeep        ),
       .s_axis_rxd_6_tlast             (s_axis_rxd_6_tlast        ),
       .s_axis_rxd_6_tvalid            (s_axis_rxd_6_tvalid       ),
       .s_axis_rxd_7_tready            (s_axis_rxd_7_tready       ),
       .s_axis_rxd_7_tdata             (s_axis_rxd_7_tdata        ),
       .s_axis_rxd_7_tuser             (s_axis_rxd_7_tuser        ),
       .s_axis_rxd_7_tkeep             (s_axis_rxd_7_tkeep        ),
       .s_axis_rxd_7_tlast             (s_axis_rxd_7_tlast        ),
       .s_axis_rxd_7_tvalid            (s_axis_rxd_7_tvalid       ),
       .s_axis_rxs_0_tready            (s_axis_rxs_0_tready       ),
       .s_axis_rxs_0_tdata             (s_axis_rxs_0_tdata        ),
       .s_axis_rxs_0_tkeep             (s_axis_rxs_0_tkeep        ),
       .s_axis_rxs_0_tlast             (s_axis_rxs_0_tlast        ),
       .s_axis_rxs_0_tvalid            (s_axis_rxs_0_tvalid       ),
       .s_axis_rxs_1_tready            (s_axis_rxs_1_tready       ),
       .s_axis_rxs_1_tdata             (s_axis_rxs_1_tdata        ),
       .s_axis_rxs_1_tkeep             (s_axis_rxs_1_tkeep        ),
       .s_axis_rxs_1_tlast             (s_axis_rxs_1_tlast        ),
       .s_axis_rxs_1_tvalid            (s_axis_rxs_1_tvalid       ),
       .s_axis_rxs_2_tready            (s_axis_rxs_2_tready       ),
       .s_axis_rxs_2_tdata             (s_axis_rxs_2_tdata        ),
       .s_axis_rxs_2_tkeep             (s_axis_rxs_2_tkeep        ),
       .s_axis_rxs_2_tlast             (s_axis_rxs_2_tlast        ),
       .s_axis_rxs_2_tvalid            (s_axis_rxs_2_tvalid       ),
       .s_axis_rxs_3_tready            (s_axis_rxs_3_tready       ),
       .s_axis_rxs_3_tdata             (s_axis_rxs_3_tdata        ),
       .s_axis_rxs_3_tkeep             (s_axis_rxs_3_tkeep        ),
       .s_axis_rxs_3_tlast             (s_axis_rxs_3_tlast        ),
       .s_axis_rxs_3_tvalid            (s_axis_rxs_3_tvalid       ),
       .s_axis_rxs_4_tready            (s_axis_rxs_4_tready       ),
       .s_axis_rxs_4_tdata             (s_axis_rxs_4_tdata        ),
       .s_axis_rxs_4_tkeep             (s_axis_rxs_4_tkeep        ),
       .s_axis_rxs_4_tlast             (s_axis_rxs_4_tlast        ),
       .s_axis_rxs_4_tvalid            (s_axis_rxs_4_tvalid       ),
       .s_axis_rxs_5_tready            (s_axis_rxs_5_tready       ),
       .s_axis_rxs_5_tdata             (s_axis_rxs_5_tdata        ),
       .s_axis_rxs_5_tkeep             (s_axis_rxs_5_tkeep        ),
       .s_axis_rxs_5_tlast             (s_axis_rxs_5_tlast        ),
       .s_axis_rxs_5_tvalid            (s_axis_rxs_5_tvalid       ),
       .s_axis_rxs_6_tready            (s_axis_rxs_6_tready       ),
       .s_axis_rxs_6_tdata             (s_axis_rxs_6_tdata        ),
       .s_axis_rxs_6_tkeep             (s_axis_rxs_6_tkeep        ),
       .s_axis_rxs_6_tlast             (s_axis_rxs_6_tlast        ),
       .s_axis_rxs_6_tvalid            (s_axis_rxs_6_tvalid       ),
       .s_axis_rxs_7_tready            (s_axis_rxs_7_tready       ),
       .s_axis_rxs_7_tdata             (s_axis_rxs_7_tdata        ),
       .s_axis_rxs_7_tkeep             (s_axis_rxs_7_tkeep        ),
       .s_axis_rxs_7_tlast             (s_axis_rxs_7_tlast        ),
       .s_axis_rxs_7_tvalid            (s_axis_rxs_7_tvalid       ),
       .s_axis_mm2s_0_tready           (s_axis_mm2s_0_tready      ),
       .s_axis_mm2s_0_tdata            (s_axis_mm2s_0_tdata       ),
       .s_axis_mm2s_0_tuser            (s_axis_mm2s_0_tuser       ),
       .s_axis_mm2s_0_tkeep            (s_axis_mm2s_0_tkeep       ),
       .s_axis_mm2s_0_tlast            (s_axis_mm2s_0_tlast       ),
       .s_axis_mm2s_0_tvalid           (s_axis_mm2s_0_tvalid      ),
       .s_axis_mm2s_1_tready           (s_axis_mm2s_1_tready      ),
       .s_axis_mm2s_1_tdata            (s_axis_mm2s_1_tdata       ),
       .s_axis_mm2s_1_tuser            (s_axis_mm2s_1_tuser       ),
       .s_axis_mm2s_1_tkeep            (s_axis_mm2s_1_tkeep       ),
       .s_axis_mm2s_1_tlast            (s_axis_mm2s_1_tlast       ),
       .s_axis_mm2s_1_tvalid           (s_axis_mm2s_1_tvalid      ),
       .s_axis_mm2s_2_tready           (s_axis_mm2s_2_tready      ),
       .s_axis_mm2s_2_tdata            (s_axis_mm2s_2_tdata       ),
       .s_axis_mm2s_2_tuser            (s_axis_mm2s_2_tuser       ),
       .s_axis_mm2s_2_tkeep            (s_axis_mm2s_2_tkeep       ),
       .s_axis_mm2s_2_tlast            (s_axis_mm2s_2_tlast       ),
       .s_axis_mm2s_2_tvalid           (s_axis_mm2s_2_tvalid      ),
       .s_axis_mm2s_3_tready           (s_axis_mm2s_3_tready      ),
       .s_axis_mm2s_3_tdata            (s_axis_mm2s_3_tdata       ),
       .s_axis_mm2s_3_tuser            (s_axis_mm2s_3_tuser       ),
       .s_axis_mm2s_3_tkeep            (s_axis_mm2s_3_tkeep       ),
       .s_axis_mm2s_3_tlast            (s_axis_mm2s_3_tlast       ),
       .s_axis_mm2s_3_tvalid           (s_axis_mm2s_3_tvalid      ),
       .s_axis_mm2s_4_tready           (s_axis_mm2s_4_tready      ),
       .s_axis_mm2s_4_tdata            (s_axis_mm2s_4_tdata       ),
       .s_axis_mm2s_4_tuser            (s_axis_mm2s_4_tuser       ),
       .s_axis_mm2s_4_tkeep            (s_axis_mm2s_4_tkeep       ),
       .s_axis_mm2s_4_tlast            (s_axis_mm2s_4_tlast       ),
       .s_axis_mm2s_4_tvalid           (s_axis_mm2s_4_tvalid      ),
       .s_axis_mm2s_5_tready           (s_axis_mm2s_5_tready      ),
       .s_axis_mm2s_5_tdata            (s_axis_mm2s_5_tdata       ),
       .s_axis_mm2s_5_tuser            (s_axis_mm2s_5_tuser       ),
       .s_axis_mm2s_5_tkeep            (s_axis_mm2s_5_tkeep       ),
       .s_axis_mm2s_5_tlast            (s_axis_mm2s_5_tlast       ),
       .s_axis_mm2s_5_tvalid           (s_axis_mm2s_5_tvalid      ),
       .s_axis_mm2s_6_tready           (s_axis_mm2s_6_tready      ),
       .s_axis_mm2s_6_tdata            (s_axis_mm2s_6_tdata       ),
       .s_axis_mm2s_6_tuser            (s_axis_mm2s_6_tuser       ),
       .s_axis_mm2s_6_tkeep            (s_axis_mm2s_6_tkeep       ),
       .s_axis_mm2s_6_tlast            (s_axis_mm2s_6_tlast       ),
       .s_axis_mm2s_6_tvalid           (s_axis_mm2s_6_tvalid      ),
       .s_axis_mm2s_7_tready           (s_axis_mm2s_7_tready      ),
       .s_axis_mm2s_7_tdata            (s_axis_mm2s_7_tdata       ),
       .s_axis_mm2s_7_tuser            (s_axis_mm2s_7_tuser       ),
       .s_axis_mm2s_7_tkeep            (s_axis_mm2s_7_tkeep       ),
       .s_axis_mm2s_7_tlast            (s_axis_mm2s_7_tlast       ),
       .s_axis_mm2s_7_tvalid           (s_axis_mm2s_7_tvalid      ),
       .s_axis_ctrl_0_tready           (s_axis_ctrl_0_tready      ),
       .s_axis_ctrl_0_tdata            (s_axis_ctrl_0_tdata       ),
       .s_axis_ctrl_0_tkeep            (s_axis_ctrl_0_tkeep       ),
       .s_axis_ctrl_0_tlast            (s_axis_ctrl_0_tlast       ),
       .s_axis_ctrl_0_tvalid           (s_axis_ctrl_0_tvalid      ),
       .s_axis_ctrl_1_tready           (s_axis_ctrl_1_tready      ),
       .s_axis_ctrl_1_tdata            (s_axis_ctrl_1_tdata       ),
       .s_axis_ctrl_1_tkeep            (s_axis_ctrl_1_tkeep       ),
       .s_axis_ctrl_1_tlast            (s_axis_ctrl_1_tlast       ),
       .s_axis_ctrl_1_tvalid           (s_axis_ctrl_1_tvalid      ),
       .s_axis_ctrl_2_tready           (s_axis_ctrl_2_tready      ),
       .s_axis_ctrl_2_tdata            (s_axis_ctrl_2_tdata       ),
       .s_axis_ctrl_2_tkeep            (s_axis_ctrl_2_tkeep       ),
       .s_axis_ctrl_2_tlast            (s_axis_ctrl_2_tlast       ),
       .s_axis_ctrl_2_tvalid           (s_axis_ctrl_2_tvalid      ),
       .s_axis_ctrl_3_tready           (s_axis_ctrl_3_tready      ),
       .s_axis_ctrl_3_tdata            (s_axis_ctrl_3_tdata       ),
       .s_axis_ctrl_3_tkeep            (s_axis_ctrl_3_tkeep       ),
       .s_axis_ctrl_3_tlast            (s_axis_ctrl_3_tlast       ),
       .s_axis_ctrl_3_tvalid           (s_axis_ctrl_3_tvalid      ),
       .s_axis_ctrl_4_tready           (s_axis_ctrl_4_tready      ),
       .s_axis_ctrl_4_tdata            (s_axis_ctrl_4_tdata       ),
       .s_axis_ctrl_4_tkeep            (s_axis_ctrl_4_tkeep       ),
       .s_axis_ctrl_4_tlast            (s_axis_ctrl_4_tlast       ),
       .s_axis_ctrl_4_tvalid           (s_axis_ctrl_4_tvalid      ),
       .s_axis_ctrl_5_tready           (s_axis_ctrl_5_tready      ),
       .s_axis_ctrl_5_tdata            (s_axis_ctrl_5_tdata       ),
       .s_axis_ctrl_5_tkeep            (s_axis_ctrl_5_tkeep       ),
       .s_axis_ctrl_5_tlast            (s_axis_ctrl_5_tlast       ),
       .s_axis_ctrl_5_tvalid           (s_axis_ctrl_5_tvalid      ),
       .s_axis_ctrl_6_tready           (s_axis_ctrl_6_tready      ),
       .s_axis_ctrl_6_tdata            (s_axis_ctrl_6_tdata       ),
       .s_axis_ctrl_6_tkeep            (s_axis_ctrl_6_tkeep       ),
       .s_axis_ctrl_6_tlast            (s_axis_ctrl_6_tlast       ),
       .s_axis_ctrl_6_tvalid           (s_axis_ctrl_6_tvalid      ),
       .s_axis_ctrl_7_tready           (s_axis_ctrl_7_tready      ),
       .s_axis_ctrl_7_tdata            (s_axis_ctrl_7_tdata       ),
       .s_axis_ctrl_7_tkeep            (s_axis_ctrl_7_tkeep       ),
       .s_axis_ctrl_7_tlast            (s_axis_ctrl_7_tlast       ),
       .s_axis_ctrl_7_tvalid           (s_axis_ctrl_7_tvalid      ),
       .m_axis_txd_0_tvalid            (s_axis_sdnet_rxd_tvalid   ),
       .m_axis_txd_0_tdata             (s_axis_sdnet_rxd_tdata    ),
       .m_axis_txd_0_tuser             (),
       .m_axis_txd_0_tkeep             (s_axis_sdnet_rxd_tkeep    ),
       .m_axis_txd_0_tlast             (s_axis_sdnet_rxd_tlast    ),
       .m_axis_txd_0_tready	           (s_axis_sdnet_rxd_tready	  ),
       .m_axis_txc_0_tvalid            (m_axis_sdnet_txc_tvalid   ),
       .m_axis_txc_0_tdata             (m_axis_sdnet_txc_tdata    ),
       .m_axis_txc_0_tkeep             (m_axis_sdnet_txc_tkeep    ),
       .m_axis_txc_0_tlast             (m_axis_sdnet_txc_tlast    ),
       .m_axis_txc_0_tready            (m_axis_sdnet_txc_tready   ),
       .tuple_out_flowstream_data      (sdnet_metadata_in_data    ),
       .tuple_out_flowstream_valid     (sdnet_metadata_in_valid   )
   );


   OpenFlowDemo OpenFlowDemo_inst
   (
       .packet_in_instream_TVALID       (s_axis_sdnet_rxd_tvalid),
       .packet_in_instream_TREADY       (s_axis_sdnet_rxd_tready),
       .packet_in_instream_TDATA        (s_axis_sdnet_rxd_tdata ),
       .packet_in_instream_TKEEP        (s_axis_sdnet_rxd_tkeep ),
       .packet_in_instream_TLAST        (s_axis_sdnet_rxd_tlast ),
       .tuple_in_metadata_in_VALID      (sdnet_metadata_in_valid),
       .tuple_in_metadata_in_DATA       (sdnet_metadata_in_data),
       .control_S_AXI_AWADDR            (control_S_AXI_AWADDR ),
       .control_S_AXI_AWVALID           (control_S_AXI_AWVALID),
       .control_S_AXI_AWREADY           (control_S_AXI_AWREADY),
       .control_S_AXI_WDATA             (control_S_AXI_WDATA  ),
       .control_S_AXI_WSTRB             (control_S_AXI_WSTRB  ),
       .control_S_AXI_WVALID            (control_S_AXI_WVALID ),
       .control_S_AXI_WREADY            (control_S_AXI_WREADY ),
       .control_S_AXI_BRESP             (control_S_AXI_BRESP  ),
       .control_S_AXI_BVALID            (control_S_AXI_BVALID ),
       .control_S_AXI_BREADY            (control_S_AXI_BREADY ),
       .control_S_AXI_ARADDR            (control_S_AXI_ARADDR ),
       .control_S_AXI_ARVALID           (control_S_AXI_ARVALID),
       .control_S_AXI_ARREADY           (control_S_AXI_ARREADY),
       .control_S_AXI_RDATA             (control_S_AXI_RDATA  ),
       .control_S_AXI_RRESP             (control_S_AXI_RRESP  ),
       .control_S_AXI_RVALID            (control_S_AXI_RVALID ),
       .control_S_AXI_RREADY            (control_S_AXI_RREADY ),
       .enable_processing               (1'b1),
       .packet_out_outstream_TVALID     (m_axis_sdnet_txd_tvalid),
       .packet_out_outstream_TREADY     (m_axis_sdnet_txd_tready),
       .packet_out_outstream_TDATA      (m_axis_sdnet_txd_tdata ),
       .packet_out_outstream_TKEEP      (m_axis_sdnet_txd_tkeep ),
       .packet_out_outstream_TLAST      (m_axis_sdnet_txd_tlast ),
       .tuple_out_metadata_out_VALID    (sdnet_metadata_out_valid),
       .tuple_out_metadata_out_DATA     (sdnet_metadata_out_data),
       .clk_line_rst                    (clk_line_rst   ),
       .clk_line                        (clk_line       ),
       .clk_lookup_rst                  (clk_lookup_rst ),
       .clk_lookup                      (clk_lookup     ),
       .clk_control_rst                 (clk_control_rst),
       .clk_control                     (clk_control    ),
       .internal_rst_done               ()
       );

   packet_output_pipeline#(
       .C_S_AXI_LITE_DATA_WIDTH    (C_S_AXI_LITE_DATA_WIDTH),
       .C_S_AXI_LITE_ADDR_WIDTH    (C_S_AXI_LITE_ADDR_WIDTH),
       .C_S_AXIS_RXD_TDATA_WIDTH   (AXIS_SDNET_DATA_WIDTH),
       .C_S_AXIS_RXS_TDATA_WIDTH   (C_S_AXIS_RXS_TDATA_WIDTH),
       .C_M_AXIS_TXD_TDATA_WIDTH   (C_M_AXIS_TXD_TDATA_WIDTH),
       .C_M_AXIS_TXC_TDATA_WIDTH   (C_M_AXIS_TXC_TDATA_WIDTH),
       .ACTION_TUPLE_WIDTH         (ACTION_TUPLE_WIDTH)
   )
   (
       .s_axis_rxd_aclk                (s_axis_rxd_aclk          ),
       .s_axis_rxd_aresetn             (s_axis_rxd_aresetn       ),
       .s_axis_txd_aclk                (s_axis_txd_aclk          ),
       .s_axis_txd_aresetn             (s_axis_txd_aresetn       ),
       .s_axi_lite_aclk                (s_axi_lite_aclk          ),
       .s_axi_lite_aresetn             (s_axi_lite_aresetn       ),
       .s_axi_lite_awaddr              (s_axi_lite_awaddr        ),
       .s_axi_lite_awprot              (s_axi_lite_awprot        ),
       .s_axi_lite_awvalid             (s_axi_lite_awvalid       ),
       .s_axi_lite_awready             (s_axi_lite_awready       ),
       .s_axi_lite_wdata               (s_axi_lite_wdata         ),
       .s_axi_lite_wstrb               (s_axi_lite_wstrb         ),
       .s_axi_lite_wvalid              (s_axi_lite_wvalid        ),
       .s_axi_lite_wready              (s_axi_lite_wready        ),
       .s_axi_lite_bresp               (s_axi_lite_bresp         ),
       .s_axi_lite_bvalid              (s_axi_lite_bvalid        ),
       .s_axi_lite_bready              (s_axi_lite_bready        ),
       .s_axi_lite_araddr              (s_axi_lite_araddr        ),
       .s_axi_lite_arprot              (s_axi_lite_arprot        ),
       .s_axi_lite_arvalid             (s_axi_lite_arvalid       ),
       .s_axi_lite_arready             (s_axi_lite_arready       ),
       .s_axi_lite_rdata               (s_axi_lite_rdata         ),
       .s_axi_lite_rresp               (s_axi_lite_rresp         ),
       .s_axi_lite_rvalid              (s_axi_lite_rvalid        ),
       .s_axi_lite_rready              (s_axi_lite_rready        ),
       .s_axis_rxd_0_tready            (m_axis_sdnet_txd_tready  ),
       .s_axis_rxd_0_tdata             (m_axis_sdnet_txd_tdata   ),
       .s_axis_rxd_0_tkeep             (m_axis_sdnet_txd_tkeep   ),
       .s_axis_rxd_0_tlast             (m_axis_sdnet_txd_tlast   ),
       .s_axis_rxd_0_tvalid            (m_axis_sdnet_txd_tvalid  ),
       .s_axis_rxs_0_tready            (m_axis_sdnet_txc_tready  ),
       .s_axis_rxs_0_tdata             (m_axis_sdnet_txc_tdata   ),
       .s_axis_rxs_0_tkeep             (m_axis_sdnet_txc_tkeep   ),
       .s_axis_rxs_0_tlast             (m_axis_sdnet_txc_tlast   ),
       .s_axis_rxs_0_tvalid            (m_axis_sdnet_txc_tvalid  ),
       .m_axis_txd_0_tvalid            (m_axis_txd_0_tvalid      ),
       .m_axis_txd_0_tdata             (m_axis_txd_0_tdata       ),
       .m_axis_txd_0_tkeep             (m_axis_txd_0_tkeep       ),
       .m_axis_txd_0_tlast             (m_axis_txd_0_tlast       ),
       .m_axis_txd_0_tready            (m_axis_txd_0_tready      ),
       .m_axis_txd_1_tvalid            (m_axis_txd_1_tvalid      ),
       .m_axis_txd_1_tdata             (m_axis_txd_1_tdata       ),
       .m_axis_txd_1_tkeep             (m_axis_txd_1_tkeep       ),
       .m_axis_txd_1_tlast             (m_axis_txd_1_tlast       ),
       .m_axis_txd_1_tready            (m_axis_txd_1_tready      ),
       .m_axis_txd_2_tvalid            (m_axis_txd_2_tvalid      ),
       .m_axis_txd_2_tdata             (m_axis_txd_2_tdata       ),
       .m_axis_txd_2_tkeep             (m_axis_txd_2_tkeep       ),
       .m_axis_txd_2_tlast             (m_axis_txd_2_tlast       ),
       .m_axis_txd_2_tready            (m_axis_txd_2_tready      ),
       .m_axis_txd_3_tvalid            (m_axis_txd_3_tvalid      ),
       .m_axis_txd_3_tdata             (m_axis_txd_3_tdata       ),
       .m_axis_txd_3_tkeep             (m_axis_txd_3_tkeep       ),
       .m_axis_txd_3_tlast             (m_axis_txd_3_tlast       ),
       .m_axis_txd_3_tready            (m_axis_txd_3_tready      ),
       .m_axis_txd_4_tvalid            (m_axis_txd_4_tvalid      ),
       .m_axis_txd_4_tdata             (m_axis_txd_4_tdata       ),
       .m_axis_txd_4_tkeep             (m_axis_txd_4_tkeep       ),
       .m_axis_txd_4_tlast             (m_axis_txd_4_tlast       ),
       .m_axis_txd_4_tready            (m_axis_txd_4_tready      ),
       .m_axis_txd_5_tvalid            (m_axis_txd_5_tvalid      ),
       .m_axis_txd_5_tdata             (m_axis_txd_5_tdata       ),
       .m_axis_txd_5_tkeep             (m_axis_txd_5_tkeep       ),
       .m_axis_txd_5_tlast             (m_axis_txd_5_tlast       ),
       .m_axis_txd_5_tready            (m_axis_txd_5_tready      ),
       .m_axis_txd_6_tvalid            (m_axis_txd_6_tvalid      ),
       .m_axis_txd_6_tdata             (m_axis_txd_6_tdata       ),
       .m_axis_txd_6_tkeep             (m_axis_txd_6_tkeep       ),
       .m_axis_txd_6_tlast             (m_axis_txd_6_tlast       ),
       .m_axis_txd_6_tready            (m_axis_txd_6_tready      ),
       .m_axis_txd_7_tvalid            (m_axis_txd_7_tvalid      ),
       .m_axis_txd_7_tdata             (m_axis_txd_7_tdata       ),
       .m_axis_txd_7_tkeep             (m_axis_txd_7_tkeep       ),
       .m_axis_txd_7_tlast             (m_axis_txd_7_tlast       ),
       .m_axis_txd_7_tready            (m_axis_txd_7_tready      ),
       .m_axis_txc_0_tvalid            (m_axis_txc_0_tvalid      ),
       .m_axis_txc_0_tdata             (m_axis_txc_0_tdata       ),
       .m_axis_txc_0_tkeep             (m_axis_txc_0_tkeep       ),
       .m_axis_txc_0_tlast             (m_axis_txc_0_tlast       ),
       .m_axis_txc_0_tready            (m_axis_txc_0_tready      ),
       .m_axis_txc_1_tvalid            (m_axis_txc_1_tvalid      ),
       .m_axis_txc_1_tdata             (m_axis_txc_1_tdata       ),
       .m_axis_txc_1_tkeep             (m_axis_txc_1_tkeep       ),
       .m_axis_txc_1_tlast             (m_axis_txc_1_tlast       ),
       .m_axis_txc_1_tready            (m_axis_txc_1_tready      ),
       .m_axis_txc_2_tvalid            (m_axis_txc_2_tvalid      ),
       .m_axis_txc_2_tdata             (m_axis_txc_2_tdata       ),
       .m_axis_txc_2_tkeep             (m_axis_txc_2_tkeep       ),
       .m_axis_txc_2_tlast             (m_axis_txc_2_tlast       ),
       .m_axis_txc_2_tready            (m_axis_txc_2_tready      ),
       .m_axis_txc_3_tvalid            (m_axis_txc_3_tvalid      ),
       .m_axis_txc_3_tdata             (m_axis_txc_3_tdata       ),
       .m_axis_txc_3_tkeep             (m_axis_txc_3_tkeep       ),
       .m_axis_txc_3_tlast             (m_axis_txc_3_tlast       ),
       .m_axis_txc_3_tready            (m_axis_txc_3_tready      ),
       .m_axis_txc_4_tvalid            (m_axis_txc_4_tvalid      ),
       .m_axis_txc_4_tdata             (m_axis_txc_4_tdata       ),
       .m_axis_txc_4_tkeep             (m_axis_txc_4_tkeep       ),
       .m_axis_txc_4_tlast             (m_axis_txc_4_tlast       ),
       .m_axis_txc_4_tready            (m_axis_txc_4_tready      ),
       .m_axis_txc_5_tvalid            (m_axis_txc_5_tvalid      ),
       .m_axis_txc_5_tdata             (m_axis_txc_5_tdata       ),
       .m_axis_txc_5_tkeep             (m_axis_txc_5_tkeep       ),
       .m_axis_txc_5_tlast             (m_axis_txc_5_tlast       ),
       .m_axis_txc_5_tready            (m_axis_txc_5_tready      ),
       .m_axis_txc_6_tvalid            (m_axis_txc_6_tvalid      ),
       .m_axis_txc_6_tdata             (m_axis_txc_6_tdata       ),
       .m_axis_txc_6_tkeep             (m_axis_txc_6_tkeep       ),
       .m_axis_txc_6_tlast             (m_axis_txc_6_tlast       ),
       .m_axis_txc_6_tready            (m_axis_txc_6_tready      ),
       .m_axis_txc_7_tvalid            (m_axis_txc_7_tvalid      ),
       .m_axis_txc_7_tdata             (m_axis_txc_7_tdata       ),
       .m_axis_txc_7_tkeep             (m_axis_txc_7_tkeep       ),
       .m_axis_txc_7_tlast             (m_axis_txc_7_tlast       ),
       .m_axis_txc_7_tready            (m_axis_txc_7_tready      ),
       .m_axis_s2mm_0_tvalid           (m_axis_s2mm_0_tvalid     ),
       .m_axis_s2mm_0_tdata            (m_axis_s2mm_0_tdata      ),
       .m_axis_s2mm_0_tkeep            (m_axis_s2mm_0_tkeep      ),
       .m_axis_s2mm_0_tlast            (m_axis_s2mm_0_tlast      ),
       .m_axis_s2mm_0_tready           (m_axis_s2mm_0_tready     ),
       .m_axis_s2mm_1_tvalid           (m_axis_s2mm_1_tvalid     ),
       .m_axis_s2mm_1_tdata            (m_axis_s2mm_1_tdata      ),
       .m_axis_s2mm_1_tkeep            (m_axis_s2mm_1_tkeep      ),
       .m_axis_s2mm_1_tlast            (m_axis_s2mm_1_tlast      ),
       .m_axis_s2mm_1_tready           (m_axis_s2mm_1_tready     ),
       .m_axis_s2mm_2_tvalid           (m_axis_s2mm_2_tvalid     ),
       .m_axis_s2mm_2_tdata            (m_axis_s2mm_2_tdata      ),
       .m_axis_s2mm_2_tkeep            (m_axis_s2mm_2_tkeep      ),
       .m_axis_s2mm_2_tlast            (m_axis_s2mm_2_tlast      ),
       .m_axis_s2mm_2_tready           (m_axis_s2mm_2_tready     ),
       .m_axis_s2mm_3_tvalid           (m_axis_s2mm_3_tvalid     ),
       .m_axis_s2mm_3_tdata            (m_axis_s2mm_3_tdata      ),
       .m_axis_s2mm_3_tkeep            (m_axis_s2mm_3_tkeep      ),
       .m_axis_s2mm_3_tlast            (m_axis_s2mm_3_tlast      ),
       .m_axis_s2mm_3_tready           (m_axis_s2mm_3_tready     ),
       .m_axis_s2mm_4_tvalid           (m_axis_s2mm_4_tvalid     ),
       .m_axis_s2mm_4_tdata            (m_axis_s2mm_4_tdata      ),
       .m_axis_s2mm_4_tkeep            (m_axis_s2mm_4_tkeep      ),
       .m_axis_s2mm_4_tlast            (m_axis_s2mm_4_tlast      ),
       .m_axis_s2mm_4_tready           (m_axis_s2mm_4_tready     ),
       .m_axis_s2mm_5_tvalid           (m_axis_s2mm_5_tvalid     ),
       .m_axis_s2mm_5_tdata            (m_axis_s2mm_5_tdata      ),
       .m_axis_s2mm_5_tkeep            (m_axis_s2mm_5_tkeep      ),
       .m_axis_s2mm_5_tlast            (m_axis_s2mm_5_tlast      ),
       .m_axis_s2mm_5_tready           (m_axis_s2mm_5_tready     ),
       .m_axis_s2mm_6_tvalid           (m_axis_s2mm_6_tvalid     ),
       .m_axis_s2mm_6_tdata            (m_axis_s2mm_6_tdata      ),
       .m_axis_s2mm_6_tkeep            (m_axis_s2mm_6_tkeep      ),
       .m_axis_s2mm_6_tlast            (m_axis_s2mm_6_tlast      ),
       .m_axis_s2mm_6_tready           (m_axis_s2mm_6_tready     ),
       .m_axis_s2mm_7_tvalid           (m_axis_s2mm_7_tvalid     ),
       .m_axis_s2mm_7_tdata            (m_axis_s2mm_7_tdata      ),
       .m_axis_s2mm_7_tkeep            (m_axis_s2mm_7_tkeep      ),
       .m_axis_s2mm_7_tlast            (m_axis_s2mm_7_tlast      ),
       .m_axis_s2mm_7_tready           (m_axis_s2mm_7_tready     ),
       .m_axis_s2mm_sts_0_tvalid       (m_axis_s2mm_sts_0_tvalid ),
       .m_axis_s2mm_sts_0_tdata        (m_axis_s2mm_sts_0_tdata  ),
       .m_axis_s2mm_sts_0_tkeep        (m_axis_s2mm_sts_0_tkeep  ),
       .m_axis_s2mm_sts_0_tlast        (m_axis_s2mm_sts_0_tlast  ),
       .m_axis_s2mm_sts_0_tready       (m_axis_s2mm_sts_0_tready ),
       .m_axis_s2mm_sts_1_tvalid       (m_axis_s2mm_sts_1_tvalid ),
       .m_axis_s2mm_sts_1_tdata        (m_axis_s2mm_sts_1_tdata  ),
       .m_axis_s2mm_sts_1_tkeep        (m_axis_s2mm_sts_1_tkeep  ),
       .m_axis_s2mm_sts_1_tlast        (m_axis_s2mm_sts_1_tlast  ),
       .m_axis_s2mm_sts_1_tready       (m_axis_s2mm_sts_1_tready ),
       .m_axis_s2mm_sts_2_tvalid       (m_axis_s2mm_sts_2_tvalid ),
       .m_axis_s2mm_sts_2_tdata        (m_axis_s2mm_sts_2_tdata  ),
       .m_axis_s2mm_sts_2_tkeep        (m_axis_s2mm_sts_2_tkeep  ),
       .m_axis_s2mm_sts_2_tlast        (m_axis_s2mm_sts_2_tlast  ),
       .m_axis_s2mm_sts_2_tready       (m_axis_s2mm_sts_2_tready ),
       .m_axis_s2mm_sts_3_tvalid       (m_axis_s2mm_sts_3_tvalid ),
       .m_axis_s2mm_sts_3_tdata        (m_axis_s2mm_sts_3_tdata  ),
       .m_axis_s2mm_sts_3_tkeep        (m_axis_s2mm_sts_3_tkeep  ),
       .m_axis_s2mm_sts_3_tlast        (m_axis_s2mm_sts_3_tlast  ),
       .m_axis_s2mm_sts_3_tready       (m_axis_s2mm_sts_3_tready ),
       .m_axis_s2mm_sts_4_tvalid       (m_axis_s2mm_sts_4_tvalid ),
       .m_axis_s2mm_sts_4_tdata        (m_axis_s2mm_sts_4_tdata  ),
       .m_axis_s2mm_sts_4_tkeep        (m_axis_s2mm_sts_4_tkeep  ),
       .m_axis_s2mm_sts_4_tlast        (m_axis_s2mm_sts_4_tlast  ),
       .m_axis_s2mm_sts_4_tready       (m_axis_s2mm_sts_4_tready ),
       .m_axis_s2mm_sts_5_tvalid       (m_axis_s2mm_sts_5_tvalid ),
       .m_axis_s2mm_sts_5_tdata        (m_axis_s2mm_sts_5_tdata  ),
       .m_axis_s2mm_sts_5_tkeep        (m_axis_s2mm_sts_5_tkeep  ),
       .m_axis_s2mm_sts_5_tlast        (m_axis_s2mm_sts_5_tlast  ),
       .m_axis_s2mm_sts_5_tready       (m_axis_s2mm_sts_5_tready ),
       .m_axis_s2mm_sts_6_tvalid       (m_axis_s2mm_sts_6_tvalid ),
       .m_axis_s2mm_sts_6_tdata        (m_axis_s2mm_sts_6_tdata  ),
       .m_axis_s2mm_sts_6_tkeep        (m_axis_s2mm_sts_6_tkeep  ),
       .m_axis_s2mm_sts_6_tlast        (m_axis_s2mm_sts_6_tlast  ),
       .m_axis_s2mm_sts_6_tready       (m_axis_s2mm_sts_6_tready ),
       .m_axis_s2mm_sts_7_tvalid       (m_axis_s2mm_sts_7_tvalid ),
       .m_axis_s2mm_sts_7_tdata        (m_axis_s2mm_sts_7_tdata  ),
       .m_axis_s2mm_sts_7_tkeep        (m_axis_s2mm_sts_7_tkeep  ),
       .m_axis_s2mm_sts_7_tlast        (m_axis_s2mm_sts_7_tlast  ),
       .m_axis_s2mm_sts_7_tready       (m_axis_s2mm_sts_7_tready ),
       .tuple_in_flowstream_data       (sdnet_metadata_out_data  ),
       .tuple_in_flowstream_valid      (sdnet_metadata_out_valid )

   );

   endmodule
